export interface BpCatalogEntry {
  odId: string;
  group: string;
  subgroup: string;
  name: string;
  desc: string;
}

/**
 * SOF-381 — OD master business-process catalog (`db.bpCatalog`, 385 rows),
 * transcribed verbatim from `bpCatSeedIfNeeded()` (open-design modules.js:2026-2043:
 * the 65-row `G` seed plus the 320-row `BPCAT_SEED` group/sub-group import).
 * Flat catalog — OD has no parent/child id refs; hierarchy is the
 * (group, subgroup) pair on each row.
 */
export const BP_CATALOG: BpCatalogEntry[] = [
  { odId: "BPC-1001", group: "Software Development", subgroup: "General", name: "Front End Development", desc: "Client-side application development — UI implementation and browser delivery." },
  { odId: "BPC-1002", group: "Software Development", subgroup: "General", name: "Back End Development", desc: "Server-side logic, APIs and integrations." },
  { odId: "BPC-1003", group: "Software Development", subgroup: "General", name: "Mobile Development", desc: "Native and cross-platform mobile applications." },
  { odId: "BPC-1004", group: "Software Development", subgroup: "General", name: "Solution Architecture", desc: "System and solution design, standards and technical direction." },
  { odId: "BPC-1005", group: "Software Development", subgroup: "General", name: "Requirements Management", desc: "Elicit, document and manage functional and non-functional requirements." },
  { odId: "BPC-1006", group: "Software Development", subgroup: "General", name: "Software Testing", desc: "Test planning, execution and defect management (QA)." },
  { odId: "BPC-1007", group: "Software Development", subgroup: "General", name: "Release Management", desc: "Coordinate builds, versioning and production releases." },
  { odId: "BPC-1008", group: "Software Development", subgroup: "General", name: "Configuration Management", desc: "Control of configuration items, baselines and environments." },
  { odId: "BPC-1009", group: "Software Development", subgroup: "General", name: "Change Management", desc: "Assess, approve and implement changes in a controlled way." },
  { odId: "BPC-1010", group: "Software Development", subgroup: "General", name: "DevOps & CI/CD", desc: "Build/deploy pipelines, automation and environment provisioning." },
  { odId: "BPC-1011", group: "IT Operations & Security", subgroup: "General", name: "Systems Administration", desc: "Server, OS and platform operations and maintenance." },
  { odId: "BPC-1012", group: "IT Operations & Security", subgroup: "General", name: "Network Administration", desc: "Network provisioning, monitoring and connectivity." },
  { odId: "BPC-1013", group: "IT Operations & Security", subgroup: "General", name: "Database Administration", desc: "Database operation, tuning, integrity and availability." },
  { odId: "BPC-1014", group: "IT Operations & Security", subgroup: "General", name: "Access Management", desc: "Identity, authentication and authorization control." },
  { odId: "BPC-1015", group: "IT Operations & Security", subgroup: "General", name: "Security Operations", desc: "Monitoring, detection and security event handling." },
  { odId: "BPC-1016", group: "IT Operations & Security", subgroup: "General", name: "Vulnerability Assessment", desc: "Identify, evaluate and track technical vulnerabilities." },
  { odId: "BPC-1017", group: "IT Operations & Security", subgroup: "General", name: "Incident Response", desc: "Detect, contain and resolve security/IT incidents." },
  { odId: "BPC-1018", group: "IT Operations & Security", subgroup: "General", name: "IT Service Desk", desc: "First-line IT support and request fulfilment." },
  { odId: "BPC-1019", group: "IT Operations & Security", subgroup: "General", name: "Backup & Recovery", desc: "Data backup, restoration and continuity of IT services." },
  { odId: "BPC-1020", group: "Governance, Risk & Compliance", subgroup: "General", name: "Management Review", desc: "Top-management review of the management system." },
  { odId: "BPC-1021", group: "Governance, Risk & Compliance", subgroup: "General", name: "Internal Audit", desc: "Planned internal audits of processes and controls." },
  { odId: "BPC-1022", group: "Governance, Risk & Compliance", subgroup: "General", name: "Risk Management", desc: "Identification, assessment and treatment of risks." },
  { odId: "BPC-1023", group: "Governance, Risk & Compliance", subgroup: "General", name: "Compliance Obligations", desc: "Identify and manage legal, regulatory and other obligations." },
  { odId: "BPC-1024", group: "Governance, Risk & Compliance", subgroup: "General", name: "Document & Records Control", desc: "Control of documented information and records." },
  { odId: "BPC-1025", group: "Governance, Risk & Compliance", subgroup: "General", name: "Policy Management", desc: "Author, approve and maintain organizational policies." },
  { odId: "BPC-1026", group: "Governance, Risk & Compliance", subgroup: "General", name: "Business Continuity", desc: "Continuity planning and resilience of critical operations." },
  { odId: "BPC-1027", group: "Quality & Operations", subgroup: "General", name: "Service / Production Delivery", desc: "Core delivery of products or services to customers." },
  { odId: "BPC-1028", group: "Quality & Operations", subgroup: "General", name: "Quality Assurance", desc: "Assurance activities that build quality into the process." },
  { odId: "BPC-1029", group: "Quality & Operations", subgroup: "General", name: "Quality Control & Inspection", desc: "Inspection, testing and acceptance of outputs." },
  { odId: "BPC-1030", group: "Quality & Operations", subgroup: "General", name: "Nonconformity & Corrective Action", desc: "Handle nonconformities and drive corrective action." },
  { odId: "BPC-1031", group: "Quality & Operations", subgroup: "General", name: "Continual Improvement", desc: "Identify and implement improvement opportunities." },
  { odId: "BPC-1032", group: "Quality & Operations", subgroup: "General", name: "Calibration & Maintenance", desc: "Maintenance and calibration of equipment and assets." },
  { odId: "BPC-1033", group: "Quality & Operations", subgroup: "General", name: "Supplier Quality", desc: "Qualify and monitor supplier quality performance." },
  { odId: "BPC-1034", group: "Commercial & Sales", subgroup: "General", name: "Lead & Opportunity Management", desc: "Capture and qualify leads and sales opportunities." },
  { odId: "BPC-1035", group: "Commercial & Sales", subgroup: "General", name: "Proposal & Quotation", desc: "Prepare proposals, quotations and pricing." },
  { odId: "BPC-1036", group: "Commercial & Sales", subgroup: "General", name: "Contract Management", desc: "Negotiate, issue and administer contracts." },
  { odId: "BPC-1037", group: "Commercial & Sales", subgroup: "General", name: "Customer Relationship Management", desc: "Manage customer accounts and relationships." },
  { odId: "BPC-1038", group: "Commercial & Sales", subgroup: "General", name: "Marketing & Communications", desc: "Brand, demand generation and communications." },
  { odId: "BPC-1039", group: "Commercial & Sales", subgroup: "General", name: "Order Management", desc: "Order capture, fulfilment and tracking." },
  { odId: "BPC-1040", group: "Procurement & Supply Chain", subgroup: "General", name: "Sourcing & Procurement", desc: "Sourcing, purchasing and requisition-to-order." },
  { odId: "BPC-1041", group: "Procurement & Supply Chain", subgroup: "General", name: "Supplier & Vendor Management", desc: "Onboard, evaluate and manage suppliers." },
  { odId: "BPC-1042", group: "Procurement & Supply Chain", subgroup: "General", name: "Inventory Management", desc: "Stock control and replenishment." },
  { odId: "BPC-1043", group: "Procurement & Supply Chain", subgroup: "General", name: "Logistics & Distribution", desc: "Warehousing, shipping and distribution." },
  { odId: "BPC-1044", group: "Procurement & Supply Chain", subgroup: "General", name: "Asset Management", desc: "Lifecycle management of physical and IT assets." },
  { odId: "BPC-1045", group: "Human Resources", subgroup: "General", name: "Recruitment & Onboarding", desc: "Hiring and onboarding of personnel." },
  { odId: "BPC-1046", group: "Human Resources", subgroup: "General", name: "Training & Competence", desc: "Competence development and training delivery." },
  { odId: "BPC-1047", group: "Human Resources", subgroup: "General", name: "Performance Management", desc: "Objectives, appraisal and performance reviews." },
  { odId: "BPC-1048", group: "Human Resources", subgroup: "General", name: "Payroll Administration", desc: "Payroll processing and disbursement." },
  { odId: "BPC-1049", group: "Human Resources", subgroup: "General", name: "Employee Relations & Disciplinary", desc: "Grievances, discipline and employee relations." },
  { odId: "BPC-1050", group: "Human Resources", subgroup: "General", name: "Offboarding", desc: "Separation, exit and access revocation." },
  { odId: "BPC-1051", group: "Finance & Accounting", subgroup: "General", name: "General Ledger & Accounting", desc: "Journals, ledgers and period close." },
  { odId: "BPC-1052", group: "Finance & Accounting", subgroup: "General", name: "Accounts Payable", desc: "Vendor invoices and payments." },
  { odId: "BPC-1053", group: "Finance & Accounting", subgroup: "General", name: "Accounts Receivable & Billing", desc: "Invoicing and collections." },
  { odId: "BPC-1054", group: "Finance & Accounting", subgroup: "General", name: "Budgeting & Forecasting", desc: "Budgets, forecasts and variance analysis." },
  { odId: "BPC-1055", group: "Finance & Accounting", subgroup: "General", name: "Financial Reporting", desc: "Statutory and management reporting." },
  { odId: "BPC-1056", group: "Finance & Accounting", subgroup: "General", name: "Tax Management", desc: "Tax computation, filing and compliance." },
  { odId: "BPC-1057", group: "Customer & Support", subgroup: "General", name: "Customer Support", desc: "Post-sale customer assistance." },
  { odId: "BPC-1058", group: "Customer & Support", subgroup: "General", name: "Complaint & Feedback Management", desc: "Capture and resolve complaints and feedback." },
  { odId: "BPC-1059", group: "Customer & Support", subgroup: "General", name: "Warranty & Returns", desc: "Warranty claims, returns and replacements." },
  { odId: "BPC-1060", group: "Sales", subgroup: "B2B Sales", name: "Account Planning", desc: "Define account strategy, stakeholders, opportunities, and commercial approach for business customers." },
  { odId: "BPC-1061", group: "Sales", subgroup: "B2B Sales", name: "Lead Qualification", desc: "Review and qualify potential business customers based on fit, need, budget, and timing." },
  { odId: "BPC-1062", group: "Sales", subgroup: "B2B Sales", name: "Sales Opportunity Management", desc: "Track and manage sales opportunities from discovery to closing." },
  { odId: "BPC-1063", group: "Sales", subgroup: "B2B Sales", name: "Sales Meeting Management", desc: "Plan, conduct, and document meetings with prospects or customers." },
  { odId: "BPC-1064", group: "Sales", subgroup: "B2B Sales", name: "Customer Requirement Capture", desc: "Capture customer needs, business problems, and commercial expectations." },
  { odId: "BPC-1065", group: "Sales", subgroup: "B2B Sales", name: "Commercial Proposal Request", desc: "Initiate proposal preparation based on validated customer needs." },
  { odId: "BPC-1066", group: "Sales", subgroup: "B2B Sales", name: "Negotiation Management", desc: "Manage pricing, scope, terms, and commercial negotiation with customers." },
  { odId: "BPC-1067", group: "Sales", subgroup: "B2B Sales", name: "Sales Closing", desc: "Confirm customer decision, acceptance, and commercial agreement." },
  { odId: "BPC-1068", group: "Sales", subgroup: "B2B Sales", name: "Account Handover", desc: "Handover customer requirements and commitments to delivery, operations, or customer success teams." },
  { odId: "BPC-1069", group: "Sales", subgroup: "B2B Sales", name: "Account Review", desc: "Review existing customer account performance, issues, renewals, and expansion opportunities." },
  { odId: "BPC-1070", group: "Sales", subgroup: "B2C Sales", name: "Customer Inquiry Handling", desc: "Receive and respond to inquiries from individual customers." },
  { odId: "BPC-1071", group: "Sales", subgroup: "B2C Sales", name: "Product or Service Explanation", desc: "Explain product or service options, benefits, pricing, and terms to customers." },
  { odId: "BPC-1072", group: "Sales", subgroup: "B2C Sales", name: "Order Capture", desc: "Capture customer order details and required purchase information." },
  { odId: "BPC-1073", group: "Sales", subgroup: "B2C Sales", name: "Customer Confirmation", desc: "Confirm order, price, availability, delivery method, and terms with customer." },
  { odId: "BPC-1074", group: "Sales", subgroup: "B2C Sales", name: "Upsell and Cross-sell", desc: "Offer relevant additional products or services to customers." },
  { odId: "BPC-1075", group: "Sales", subgroup: "B2C Sales", name: "Sales Transaction Processing", desc: "Process customer purchase transaction and supporting records." },
  { odId: "BPC-1076", group: "Sales", subgroup: "B2C Sales", name: "Customer Follow-up", desc: "Follow up with customers after inquiry, quotation, or purchase." },
  { odId: "BPC-1077", group: "Sales", subgroup: "B2C Sales", name: "Customer Retention", desc: "Maintain customer engagement to encourage repeat purchase." },
  { odId: "BPC-1078", group: "Sales", subgroup: "B2C Sales", name: "Sales Issue Escalation", desc: "Escalate pricing, fulfillment, or customer issues to relevant functions." },
  { odId: "BPC-1079", group: "Sales", subgroup: "B2C Sales", name: "Sales Performance Review", desc: "Review individual/customer sales activity and outcomes." },
  { odId: "BPC-1080", group: "Sales", subgroup: "Pre-Sales", name: "Pre-Sales Discovery", desc: "Understand customer needs, pain points, requirements, and expected outcomes." },
  { odId: "BPC-1081", group: "Sales", subgroup: "Pre-Sales", name: "Solution Fit Assessment", desc: "Assess whether available products or services can meet customer requirements." },
  { odId: "BPC-1082", group: "Sales", subgroup: "Pre-Sales", name: "Demo Preparation", desc: "Prepare demonstration materials, scenarios, and talking points." },
  { odId: "BPC-1083", group: "Sales", subgroup: "Pre-Sales", name: "Product Demonstration", desc: "Deliver product or service demonstration to prospects or customers." },
  { odId: "BPC-1084", group: "Sales", subgroup: "Pre-Sales", name: "Pre-Sales Consultation", desc: "Provide advisory input before formal proposal or purchase decision." },
  { odId: "BPC-1085", group: "Sales", subgroup: "Pre-Sales", name: "Requirement Clarification", desc: "Clarify technical, operational, commercial, or compliance requirements." },
  { odId: "BPC-1086", group: "Sales", subgroup: "Pre-Sales", name: "Preliminary Scope Definition", desc: "Define preliminary scope, assumptions, exclusions, and dependencies." },
  { odId: "BPC-1087", group: "Sales", subgroup: "Pre-Sales", name: "Proposal Input Preparation", desc: "Provide technical or solution input for proposal development." },
  { odId: "BPC-1088", group: "Sales", subgroup: "Pre-Sales", name: "Customer Objection Handling", desc: "Address customer concerns before purchase decision." },
  { odId: "BPC-1089", group: "Sales", subgroup: "Pre-Sales", name: "Pre-Sales Handover", desc: "Handover confirmed requirements to sales or delivery team." },
  { odId: "BPC-1090", group: "Sales", subgroup: "Sales Engineering", name: "Solution Design Support", desc: "Support sales by preparing solution design or configuration." },
  { odId: "BPC-1091", group: "Sales", subgroup: "Sales Engineering", name: "Technical Feasibility Review", desc: "Review whether proposed solution is technically feasible." },
  { odId: "BPC-1092", group: "Sales", subgroup: "Sales Engineering", name: "Technical Requirement Mapping", desc: "Map customer technical requirements to available solutions." },
  { odId: "BPC-1093", group: "Sales", subgroup: "Sales Engineering", name: "Proof of Concept Support", desc: "Support limited trial or proof of concept activities." },
  { odId: "BPC-1094", group: "Sales", subgroup: "Sales Engineering", name: "Technical Proposal Support", desc: "Prepare technical content for proposal or quotation." },
  { odId: "BPC-1095", group: "Sales", subgroup: "Sales Engineering", name: "Integration Requirement Review", desc: "Review required integration points, dependencies, and constraints." },
  { odId: "BPC-1096", group: "Sales", subgroup: "Sales Engineering", name: "Technical Risk Identification", desc: "Identify technical risks during sales or proposal stage." },
  { odId: "BPC-1097", group: "Sales", subgroup: "Sales Engineering", name: "Implementation Effort Estimation", desc: "Estimate technical effort, resources, or implementation complexity." },
  { odId: "BPC-1098", group: "Sales", subgroup: "Sales Engineering", name: "Technical Clarification Response", desc: "Respond to technical questions from customers or prospects." },
  { odId: "BPC-1099", group: "Sales", subgroup: "Sales Engineering", name: "Sales-to-Delivery Technical Handover", desc: "Handover technical assumptions and commitments to delivery team." },
  { odId: "BPC-1100", group: "Marketing", subgroup: "Digital Marketing", name: "Digital Campaign Planning", desc: "Plan online campaigns across paid, owned, and earned digital channels." },
  { odId: "BPC-1101", group: "Marketing", subgroup: "Digital Marketing", name: "Website Content Management", desc: "Create, update, and manage website content." },
  { odId: "BPC-1102", group: "Marketing", subgroup: "Digital Marketing", name: "Search Engine Optimization", desc: "Improve discoverability of website and digital content." },
  { odId: "BPC-1103", group: "Marketing", subgroup: "Digital Marketing", name: "Paid Advertising Management", desc: "Plan, run, monitor, and optimize paid advertising campaigns." },
  { odId: "BPC-1104", group: "Marketing", subgroup: "Digital Marketing", name: "Landing Page Management", desc: "Create and optimize landing pages for campaigns or offerings." },
  { odId: "BPC-1105", group: "Marketing", subgroup: "Digital Marketing", name: "Email Marketing", desc: "Plan and send email campaigns to target audiences." },
  { odId: "BPC-1106", group: "Marketing", subgroup: "Digital Marketing", name: "Marketing Automation", desc: "Manage automated marketing workflows and audience segmentation." },
  { odId: "BPC-1107", group: "Marketing", subgroup: "Digital Marketing", name: "Campaign Performance Monitoring", desc: "Monitor traffic, conversion, engagement, and campaign results." },
  { odId: "BPC-1108", group: "Marketing", subgroup: "Digital Marketing", name: "Lead Capture Management", desc: "Capture leads from forms, campaigns, events, and digital channels." },
  { odId: "BPC-1109", group: "Marketing", subgroup: "Digital Marketing", name: "Digital Asset Management", desc: "Organize and control digital marketing assets." },
  { odId: "BPC-1110", group: "Marketing", subgroup: "Marketing Communication", name: "Brand Messaging", desc: "Define and maintain brand message, tone, and positioning." },
  { odId: "BPC-1111", group: "Marketing", subgroup: "Marketing Communication", name: "Marketing Content Planning", desc: "Plan content themes, topics, calendar, and distribution channels." },
  { odId: "BPC-1112", group: "Marketing", subgroup: "Marketing Communication", name: "Copywriting and Content Creation", desc: "Create marketing copy, articles, captions, brochures, and other content." },
  { odId: "BPC-1113", group: "Marketing", subgroup: "Marketing Communication", name: "Public Relations Support", desc: "Support external communication, media, announcements, and public messaging." },
  { odId: "BPC-1114", group: "Marketing", subgroup: "Marketing Communication", name: "Corporate Communication", desc: "Manage company-level announcements and communication materials." },
  { odId: "BPC-1115", group: "Marketing", subgroup: "Marketing Communication", name: "Campaign Communication", desc: "Prepare communication materials for marketing campaigns." },
  { odId: "BPC-1116", group: "Marketing", subgroup: "Marketing Communication", name: "Event Communication", desc: "Prepare invitations, announcements, and event-related communication." },
  { odId: "BPC-1117", group: "Marketing", subgroup: "Marketing Communication", name: "Marketing Collateral Management", desc: "Create and maintain brochures, decks, flyers, and product materials." },
  { odId: "BPC-1118", group: "Marketing", subgroup: "Marketing Communication", name: "Brand Review", desc: "Review marketing materials for brand consistency." },
  { odId: "BPC-1119", group: "Marketing", subgroup: "Marketing Communication", name: "Communication Effectiveness Review", desc: "Review effectiveness of marketing and communication activities." },
  { odId: "BPC-1120", group: "Marketing", subgroup: "Social Media Marketing", name: "Social Media Planning", desc: "Plan content themes, posting schedule, and platform focus." },
  { odId: "BPC-1121", group: "Marketing", subgroup: "Social Media Marketing", name: "Social Media Content Creation", desc: "Create posts, captions, short videos, graphics, and stories." },
  { odId: "BPC-1122", group: "Marketing", subgroup: "Social Media Marketing", name: "Social Media Publishing", desc: "Publish approved content to selected platforms." },
  { odId: "BPC-1123", group: "Marketing", subgroup: "Social Media Marketing", name: "Community Engagement", desc: "Respond to comments, messages, and audience interaction." },
  { odId: "BPC-1124", group: "Marketing", subgroup: "Social Media Marketing", name: "Social Listening", desc: "Monitor audience sentiment, mentions, trends, and competitor activity." },
  { odId: "BPC-1125", group: "Marketing", subgroup: "Social Media Marketing", name: "Influencer or Partner Coordination", desc: "Coordinate social collaboration with external parties." },
  { odId: "BPC-1126", group: "Marketing", subgroup: "Social Media Marketing", name: "Social Media Campaign Management", desc: "Run targeted social media campaigns." },
  { odId: "BPC-1127", group: "Marketing", subgroup: "Social Media Marketing", name: "Social Media Performance Review", desc: "Review engagement, reach, conversion, and content effectiveness." },
  { odId: "BPC-1128", group: "Marketing", subgroup: "Social Media Marketing", name: "Content Moderation", desc: "Review and moderate comments, posts, and community activity." },
  { odId: "BPC-1129", group: "Marketing", subgroup: "Social Media Marketing", name: "Social Media Issue Escalation", desc: "Escalate complaints, misinformation, or reputational issues." },
  { odId: "BPC-1130", group: "Marketing", subgroup: "Market Research", name: "Market Data Collection", desc: "Collect market, customer, competitor, and industry information." },
  { odId: "BPC-1131", group: "Marketing", subgroup: "Market Research", name: "Customer Insight Analysis", desc: "Analyze customer needs, behavior, preferences, and feedback." },
  { odId: "BPC-1132", group: "Marketing", subgroup: "Market Research", name: "Competitor Analysis", desc: "Review competitor offerings, pricing, positioning, and campaigns." },
  { odId: "BPC-1133", group: "Marketing", subgroup: "Market Research", name: "Market Segmentation", desc: "Define target segments and audience profiles." },
  { odId: "BPC-1134", group: "Marketing", subgroup: "Market Research", name: "Campaign Insight Review", desc: "Analyze campaign results to generate marketing insight." },
  { odId: "BPC-1135", group: "Marketing", subgroup: "Market Research", name: "Survey Management", desc: "Plan, distribute, and analyze customer or market surveys." },
  { odId: "BPC-1136", group: "Marketing", subgroup: "Market Research", name: "Trend Monitoring", desc: "Monitor market trends and relevant external changes." },
  { odId: "BPC-1137", group: "Marketing", subgroup: "Market Research", name: "Marketing Recommendation Preparation", desc: "Prepare marketing recommendations based on research findings." },
  { odId: "BPC-1138", group: "Business Development", subgroup: "Partnership Development", name: "Partner Identification", desc: "Identify potential partners, alliances, channels, or strategic collaborators." },
  { odId: "BPC-1139", group: "Business Development", subgroup: "Partnership Development", name: "Partner Qualification", desc: "Assess partner fit, capability, reputation, and commercial potential." },
  { odId: "BPC-1140", group: "Business Development", subgroup: "Partnership Development", name: "Partner Engagement", desc: "Initiate and manage communication with potential partners." },
  { odId: "BPC-1141", group: "Business Development", subgroup: "Partnership Development", name: "Partnership Proposal", desc: "Prepare partnership concept, value proposition, and collaboration proposal." },
  { odId: "BPC-1142", group: "Business Development", subgroup: "Partnership Development", name: "Partnership Negotiation", desc: "Negotiate partnership scope, responsibilities, and commercial model." },
  { odId: "BPC-1143", group: "Business Development", subgroup: "Partnership Development", name: "Partner Onboarding", desc: "Onboard approved partners into cooperation process." },
  { odId: "BPC-1144", group: "Business Development", subgroup: "Partnership Development", name: "Partner Performance Review", desc: "Review partner contribution, activity, and results." },
  { odId: "BPC-1145", group: "Business Development", subgroup: "Partnership Development", name: "Partnership Renewal or Termination", desc: "Manage continuation, renewal, or termination of partnership." },
  { odId: "BPC-1146", group: "Business Development", subgroup: "Market Expansion", name: "Market Opportunity Identification", desc: "Identify new market, segment, region, or customer opportunity." },
  { odId: "BPC-1147", group: "Business Development", subgroup: "Market Expansion", name: "Opportunity Feasibility Review", desc: "Assess feasibility, potential value, risk, and resource needs." },
  { odId: "BPC-1148", group: "Business Development", subgroup: "Market Expansion", name: "Go-to-Market Planning", desc: "Prepare strategy to enter or expand into target market." },
  { odId: "BPC-1149", group: "Business Development", subgroup: "Market Expansion", name: "New Channel Development", desc: "Develop new sales or distribution channels." },
  { odId: "BPC-1150", group: "Business Development", subgroup: "Market Expansion", name: "New Offering Exploration", desc: "Explore potential new products, services, or solution packages." },
  { odId: "BPC-1151", group: "Business Development", subgroup: "Market Expansion", name: "Commercial Model Development", desc: "Define pricing, packaging, margin, and commercial approach." },
  { odId: "BPC-1152", group: "Business Development", subgroup: "Market Expansion", name: "Business Case Preparation", desc: "Prepare business case for new opportunity or expansion." },
  { odId: "BPC-1153", group: "Business Development", subgroup: "Market Expansion", name: "Expansion Performance Review", desc: "Review outcome of market expansion initiative." },
  { odId: "BPC-1154", group: "Business Development", subgroup: "Strategic Accounts", name: "Strategic Account Identification", desc: "Identify accounts with strategic business potential." },
  { odId: "BPC-1155", group: "Business Development", subgroup: "Strategic Accounts", name: "Stakeholder Mapping", desc: "Map key decision makers, influencers, and relationship owners." },
  { odId: "BPC-1156", group: "Business Development", subgroup: "Strategic Accounts", name: "Relationship Development", desc: "Build and maintain long-term strategic business relationships." },
  { odId: "BPC-1157", group: "Business Development", subgroup: "Strategic Accounts", name: "Account Growth Planning", desc: "Plan expansion, renewal, or cross-sell opportunity." },
  { odId: "BPC-1158", group: "Business Development", subgroup: "Strategic Accounts", name: "Executive Engagement", desc: "Coordinate leadership-level engagement with strategic customers or partners." },
  { odId: "BPC-1159", group: "Business Development", subgroup: "Strategic Accounts", name: "Strategic Opportunity Review", desc: "Review major opportunities and required support." },
  { odId: "BPC-1160", group: "Business Development", subgroup: "Strategic Accounts", name: "Account Risk Review", desc: "Review commercial, relationship, delivery, or retention risks." },
  { odId: "BPC-1161", group: "Finance", subgroup: "Budgeting", name: "Budget Planning", desc: "Prepare budget assumptions, allocations, and financial targets." },
  { odId: "BPC-1162", group: "Finance", subgroup: "Budgeting", name: "Budget Request Review", desc: "Review budget requests from departments or budget owners." },
  { odId: "BPC-1163", group: "Finance", subgroup: "Budgeting", name: "Budget Approval Coordination", desc: "Coordinate approval of budget by authorized personnel." },
  { odId: "BPC-1164", group: "Finance", subgroup: "Budgeting", name: "Budget Allocation", desc: "Allocate approved budget to departments, projects, or cost centers." },
  { odId: "BPC-1165", group: "Finance", subgroup: "Budgeting", name: "Budget Revision", desc: "Update budget based on approved changes or business needs." },
  { odId: "BPC-1166", group: "Finance", subgroup: "Budgeting", name: "Budget Monitoring", desc: "Monitor budget utilization against approved budget." },
  { odId: "BPC-1167", group: "Finance", subgroup: "Budgeting", name: "Budget Variance Analysis", desc: "Analyze differences between actual spending and budget." },
  { odId: "BPC-1168", group: "Finance", subgroup: "Budgeting", name: "Budget Reporting", desc: "Prepare budget status and variance reports." },
  { odId: "BPC-1169", group: "Finance", subgroup: "Treasury", name: "Cash Flow Planning", desc: "Plan incoming and outgoing cash requirements." },
  { odId: "BPC-1170", group: "Finance", subgroup: "Treasury", name: "Cash Position Monitoring", desc: "Monitor bank balance, cash availability, and liquidity." },
  { odId: "BPC-1171", group: "Finance", subgroup: "Treasury", name: "Payment Scheduling", desc: "Schedule payments based on due dates and cash flow priority." },
  { odId: "BPC-1172", group: "Finance", subgroup: "Treasury", name: "Bank Account Management", desc: "Manage operational bank accounts and related records." },
  { odId: "BPC-1173", group: "Finance", subgroup: "Treasury", name: "Fund Transfer Processing", desc: "Process approved fund transfers." },
  { odId: "BPC-1174", group: "Finance", subgroup: "Treasury", name: "Petty Cash Management", desc: "Manage petty cash requests, disbursement, and reconciliation." },
  { odId: "BPC-1175", group: "Finance", subgroup: "Treasury", name: "Loan or Financing Administration", desc: "Administer loans, financing, or credit facilities if applicable." },
  { odId: "BPC-1176", group: "Finance", subgroup: "Treasury", name: "Treasury Reporting", desc: "Report cash position, liquidity, and payment status." },
  { odId: "BPC-1177", group: "Finance", subgroup: "Financial Control", name: "Financial Approval Review", desc: "Review financial approval based on authority limits." },
  { odId: "BPC-1178", group: "Finance", subgroup: "Financial Control", name: "Expenditure Control", desc: "Control spending against budget, approval, and policy." },
  { odId: "BPC-1179", group: "Finance", subgroup: "Financial Control", name: "Financial Risk Review", desc: "Review financial exposure, liquidity risk, or payment risk." },
  { odId: "BPC-1180", group: "Finance", subgroup: "Financial Control", name: "Cost Control", desc: "Monitor and control cost efficiency." },
  { odId: "BPC-1181", group: "Finance", subgroup: "Financial Control", name: "Financial Policy Compliance", desc: "Review compliance with internal financial policies." },
  { odId: "BPC-1182", group: "Finance", subgroup: "Financial Control", name: "Financial Exception Handling", desc: "Handle unusual, urgent, or non-standard financial requests." },
  { odId: "BPC-1183", group: "Finance", subgroup: "Financial Control", name: "Financial Performance Review", desc: "Review financial results and key performance indicators." },
  { odId: "BPC-1184", group: "Accounting", subgroup: "Accounts Payable", name: "Vendor Invoice Receipt", desc: "Receive and register vendor invoices." },
  { odId: "BPC-1185", group: "Accounting", subgroup: "Accounts Payable", name: "Invoice Verification", desc: "Verify invoice against purchase order, contract, receipt, or approval." },
  { odId: "BPC-1186", group: "Accounting", subgroup: "Accounts Payable", name: "Payable Recording", desc: "Record payable transaction in accounting system." },
  { odId: "BPC-1187", group: "Accounting", subgroup: "Accounts Payable", name: "Payment Request Preparation", desc: "Prepare payment request for approved vendor invoices." },
  { odId: "BPC-1188", group: "Accounting", subgroup: "Accounts Payable", name: "Vendor Statement Reconciliation", desc: "Reconcile vendor statements with internal records." },
  { odId: "BPC-1189", group: "Accounting", subgroup: "Accounts Payable", name: "AP Aging Review", desc: "Review outstanding payables and due dates." },
  { odId: "BPC-1190", group: "Accounting", subgroup: "Accounts Payable", name: "AP Issue Resolution", desc: "Resolve invoice mismatch, missing documents, or payment dispute." },
  { odId: "BPC-1191", group: "Accounting", subgroup: "Accounts Receivable", name: "Customer Invoice Preparation", desc: "Prepare invoices to customers based on order, contract, or service delivery." },
  { odId: "BPC-1192", group: "Accounting", subgroup: "Accounts Receivable", name: "Invoice Issuance", desc: "Issue invoice to customer through approved channel." },
  { odId: "BPC-1193", group: "Accounting", subgroup: "Accounts Receivable", name: "Receivable Recording", desc: "Record receivable transaction in accounting system." },
  { odId: "BPC-1194", group: "Accounting", subgroup: "Accounts Receivable", name: "Collection Monitoring", desc: "Monitor outstanding receivables and payment due dates." },
  { odId: "BPC-1195", group: "Accounting", subgroup: "Accounts Receivable", name: "Payment Receipt Matching", desc: "Match customer payment receipt to invoice." },
  { odId: "BPC-1196", group: "Accounting", subgroup: "Accounts Receivable", name: "AR Aging Review", desc: "Review overdue receivables and collection status." },
  { odId: "BPC-1197", group: "Accounting", subgroup: "Accounts Receivable", name: "Customer Billing Issue Resolution", desc: "Resolve billing disputes, corrections, or invoice issues." },
  { odId: "BPC-1198", group: "Accounting", subgroup: "General Ledger", name: "Journal Entry Recording", desc: "Record accounting journal entries." },
  { odId: "BPC-1199", group: "Accounting", subgroup: "General Ledger", name: "Account Reconciliation", desc: "Reconcile account balances and supporting records." },
  { odId: "BPC-1200", group: "Accounting", subgroup: "General Ledger", name: "Accrual and Prepayment Recording", desc: "Record accruals, prepayments, and period adjustments." },
  { odId: "BPC-1201", group: "Accounting", subgroup: "General Ledger", name: "Fixed Asset Accounting", desc: "Record asset acquisition, depreciation, disposal, and asset movement." },
  { odId: "BPC-1202", group: "Accounting", subgroup: "General Ledger", name: "Month-End Closing", desc: "Perform monthly accounting close activities." },
  { odId: "BPC-1203", group: "Accounting", subgroup: "General Ledger", name: "Year-End Closing", desc: "Perform year-end accounting close activities." },
  { odId: "BPC-1204", group: "Accounting", subgroup: "General Ledger", name: "Trial Balance Review", desc: "Review trial balance for completeness and accuracy." },
  { odId: "BPC-1205", group: "Accounting", subgroup: "General Ledger", name: "Financial Statement Preparation", desc: "Prepare financial statements and supporting schedules." },
  { odId: "BPC-1206", group: "Accounting", subgroup: "Accounting Records", name: "Accounting Document Filing", desc: "Store and organize accounting records and evidence." },
  { odId: "BPC-1207", group: "Accounting", subgroup: "Accounting Records", name: "Accounting Data Backup", desc: "Maintain backup of accounting data and records." },
  { odId: "BPC-1208", group: "Accounting", subgroup: "Accounting Records", name: "Supporting Document Control", desc: "Ensure accounting transactions have appropriate supporting documents." },
  { odId: "BPC-1209", group: "Accounting", subgroup: "Accounting Records", name: "Audit Support Preparation", desc: "Prepare accounting records for audit or review." },
  { odId: "BPC-1210", group: "Accounting", subgroup: "Accounting Records", name: "Record Retention Management", desc: "Retain accounting records according to retention requirements." },
  { odId: "BPC-1211", group: "Tax Compliance", subgroup: "Tax Administration", name: "Tax Data Collection", desc: "Collect tax-related transaction data and supporting records." },
  { odId: "BPC-1212", group: "Tax Compliance", subgroup: "Tax Administration", name: "Tax Calculation", desc: "Calculate applicable taxes based on transaction type and rules." },
  { odId: "BPC-1213", group: "Tax Compliance", subgroup: "Tax Administration", name: "Tax Payment Preparation", desc: "Prepare tax payment request and supporting documentation." },
  { odId: "BPC-1214", group: "Tax Compliance", subgroup: "Tax Administration", name: "Tax Filing Preparation", desc: "Prepare tax return or filing documents." },
  { odId: "BPC-1215", group: "Tax Compliance", subgroup: "Tax Administration", name: "Tax Filing Submission", desc: "Submit tax reports through applicable tax system or channel." },
  { odId: "BPC-1216", group: "Tax Compliance", subgroup: "Tax Administration", name: "Tax Payment Reconciliation", desc: "Reconcile tax payment with accounting and tax records." },
  { odId: "BPC-1217", group: "Tax Compliance", subgroup: "Tax Administration", name: "Tax Calendar Monitoring", desc: "Monitor tax deadlines and compliance calendar." },
  { odId: "BPC-1218", group: "Tax Compliance", subgroup: "Withholding Tax", name: "Withholding Tax Review", desc: "Review transactions subject to withholding tax." },
  { odId: "BPC-1219", group: "Tax Compliance", subgroup: "Withholding Tax", name: "Withholding Tax Slip Preparation", desc: "Prepare withholding tax slips or evidence." },
  { odId: "BPC-1220", group: "Tax Compliance", subgroup: "Withholding Tax", name: "Withholding Tax Reporting", desc: "Report withholding tax according to applicable deadlines." },
  { odId: "BPC-1221", group: "Tax Compliance", subgroup: "Withholding Tax", name: "Withholding Tax Reconciliation", desc: "Reconcile withholding tax records with accounting records." },
  { odId: "BPC-1222", group: "Tax Compliance", subgroup: "VAT / Indirect Tax", name: "VAT Invoice Management", desc: "Prepare, receive, and control VAT invoices or equivalent tax documents." },
  { odId: "BPC-1223", group: "Tax Compliance", subgroup: "VAT / Indirect Tax", name: "VAT Input Output Reconciliation", desc: "Reconcile VAT input and output records." },
  { odId: "BPC-1224", group: "Tax Compliance", subgroup: "VAT / Indirect Tax", name: "VAT Reporting", desc: "Prepare and submit VAT or indirect tax report." },
  { odId: "BPC-1225", group: "Tax Compliance", subgroup: "VAT / Indirect Tax", name: "VAT Correction Handling", desc: "Handle VAT correction, replacement, or adjustment records." },
  { odId: "BPC-1226", group: "Tax Compliance", subgroup: "Tax Audit & Advisory", name: "Tax Audit Support", desc: "Prepare data and support during tax audit or inquiry." },
  { odId: "BPC-1227", group: "Tax Compliance", subgroup: "Tax Audit & Advisory", name: "Tax Issue Analysis", desc: "Analyze tax issues, exposure, or unusual transactions." },
  { odId: "BPC-1228", group: "Tax Compliance", subgroup: "Tax Audit & Advisory", name: "Tax Regulation Monitoring", desc: "Monitor changes in tax laws and regulations." },
  { odId: "BPC-1229", group: "Tax Compliance", subgroup: "Tax Audit & Advisory", name: "Tax Advisory Request Handling", desc: "Provide internal tax advice for business transactions." },
  { odId: "BPC-1230", group: "Tax Compliance", subgroup: "Tax Audit & Advisory", name: "Tax Dispute Support", desc: "Support tax objection, clarification, or dispute process." },
  { odId: "BPC-1231", group: "Human Resources", subgroup: "Workforce Planning", name: "Manpower Planning", desc: "Identify staffing needs based on business plans and workload." },
  { odId: "BPC-1232", group: "Human Resources", subgroup: "Workforce Planning", name: "Job Role Definition", desc: "Define roles, responsibilities, and reporting lines." },
  { odId: "BPC-1233", group: "Human Resources", subgroup: "Workforce Planning", name: "Organization Structure Management", desc: "Maintain organization structure and position records." },
  { odId: "BPC-1234", group: "Human Resources", subgroup: "Workforce Planning", name: "Workload Review", desc: "Review staffing level and workload distribution." },
  { odId: "BPC-1235", group: "Human Resources", subgroup: "Workforce Planning", name: "Succession Planning", desc: "Identify key roles and potential successors." },
  { odId: "BPC-1236", group: "Human Resources", subgroup: "Recruitment", name: "Recruitment Request", desc: "Receive and review request to hire." },
  { odId: "BPC-1237", group: "Human Resources", subgroup: "Recruitment", name: "Job Posting", desc: "Publish job vacancy internally or externally." },
  { odId: "BPC-1238", group: "Human Resources", subgroup: "Recruitment", name: "Candidate Screening", desc: "Review applicant qualifications and shortlist candidates." },
  { odId: "BPC-1239", group: "Human Resources", subgroup: "Recruitment", name: "Interview Coordination", desc: "Schedule and coordinate interview process." },
  { odId: "BPC-1240", group: "Human Resources", subgroup: "Recruitment", name: "Candidate Assessment", desc: "Assess candidate suitability through interview, test, or review." },
  { odId: "BPC-1241", group: "Human Resources", subgroup: "Recruitment", name: "Offering and Negotiation", desc: "Prepare offer and negotiate employment terms." },
  { odId: "BPC-1242", group: "Human Resources", subgroup: "Recruitment", name: "Recruitment Closure", desc: "Close recruitment process and update hiring records." },
  { odId: "BPC-1243", group: "Human Resources", subgroup: "Onboarding", name: "New Joiner Preparation", desc: "Prepare onboarding plan, access, equipment, and documents." },
  { odId: "BPC-1244", group: "Human Resources", subgroup: "Onboarding", name: "Employment Document Collection", desc: "Collect required employment documents." },
  { odId: "BPC-1245", group: "Human Resources", subgroup: "Onboarding", name: "Orientation Session", desc: "Conduct company orientation for new personnel." },
  { odId: "BPC-1246", group: "Human Resources", subgroup: "Onboarding", name: "Policy Acknowledgment", desc: "Collect acknowledgment of policies, rules, and agreements." },
  { odId: "BPC-1247", group: "Human Resources", subgroup: "Onboarding", name: "Probation Monitoring", desc: "Monitor probation period, performance, and confirmation decision." },
  { odId: "BPC-1248", group: "Human Resources", subgroup: "Onboarding", name: "Onboarding Completion Review", desc: "Review onboarding completion and unresolved items." },
  { odId: "BPC-1249", group: "Human Resources", subgroup: "Personnel Administration", name: "Employee Data Management", desc: "Maintain employee personal, employment, and administrative data." },
  { odId: "BPC-1250", group: "Human Resources", subgroup: "Personnel Administration", name: "Attendance Administration", desc: "Manage attendance records and working time data." },
  { odId: "BPC-1251", group: "Human Resources", subgroup: "Personnel Administration", name: "Leave Administration", desc: "Manage leave requests, balances, and approvals." },
  { odId: "BPC-1252", group: "Human Resources", subgroup: "Personnel Administration", name: "Employment Contract Administration", desc: "Prepare and maintain employment contracts and amendments." },
  { odId: "BPC-1253", group: "Human Resources", subgroup: "Personnel Administration", name: "Personnel Record Retention", desc: "Maintain personnel records according to retention requirements." },
  { odId: "BPC-1254", group: "Human Resources", subgroup: "Personnel Administration", name: "Employee Letter Administration", desc: "Prepare employment letters, confirmations, and certificates." },
  { odId: "BPC-1255", group: "Human Resources", subgroup: "Performance Management", name: "Performance Objective Setting", desc: "Define individual or team performance objectives." },
  { odId: "BPC-1256", group: "Human Resources", subgroup: "Performance Management", name: "Performance Review", desc: "Conduct periodic performance evaluation." },
  { odId: "BPC-1257", group: "Human Resources", subgroup: "Performance Management", name: "Performance Feedback", desc: "Provide feedback, coaching notes, and improvement input." },
  { odId: "BPC-1258", group: "Human Resources", subgroup: "Performance Management", name: "Performance Improvement Plan", desc: "Manage improvement plan for underperformance." },
  { odId: "BPC-1259", group: "Human Resources", subgroup: "Performance Management", name: "Promotion or Role Change Review", desc: "Review eligibility for promotion, transfer, or role change." },
  { odId: "BPC-1260", group: "Human Resources", subgroup: "Learning & Development", name: "Training Need Identification", desc: "Identify training or development needs." },
  { odId: "BPC-1261", group: "Human Resources", subgroup: "Learning & Development", name: "Training Plan Management", desc: "Plan training activities, owner, participants, and schedule." },
  { odId: "BPC-1262", group: "Human Resources", subgroup: "Learning & Development", name: "Training Delivery Coordination", desc: "Coordinate delivery of internal or external training." },
  { odId: "BPC-1263", group: "Human Resources", subgroup: "Learning & Development", name: "Training Attendance Recording", desc: "Record attendance and participation." },
  { odId: "BPC-1264", group: "Human Resources", subgroup: "Learning & Development", name: "Training Evaluation", desc: "Evaluate training effectiveness or participant feedback." },
  { odId: "BPC-1265", group: "Human Resources", subgroup: "Learning & Development", name: "Competence Assessment Support", desc: "Support competence assessment and reassessment activities." },
  { odId: "BPC-1266", group: "Human Resources", subgroup: "Employee Relations", name: "Employee Communication", desc: "Manage HR-related communication with employees." },
  { odId: "BPC-1267", group: "Human Resources", subgroup: "Employee Relations", name: "Grievance Handling", desc: "Receive and handle employee concerns or grievances." },
  { odId: "BPC-1268", group: "Human Resources", subgroup: "Employee Relations", name: "Disciplinary Process", desc: "Manage disciplinary actions according to company rules." },
  { odId: "BPC-1269", group: "Human Resources", subgroup: "Employee Relations", name: "Employee Engagement", desc: "Plan and monitor employee engagement activities." },
  { odId: "BPC-1270", group: "Human Resources", subgroup: "Employee Relations", name: "Exit Management", desc: "Manage resignation, termination, clearance, and exit interview." },
  { odId: "BPC-1271", group: "Procurement", subgroup: "Purchase Request Management", name: "Purchase Request Submission", desc: "Receive purchase request from user or requesting department." },
  { odId: "BPC-1272", group: "Procurement", subgroup: "Purchase Request Management", name: "Line Manager Review", desc: "Review business need, justification, and request appropriateness." },
  { odId: "BPC-1273", group: "Procurement", subgroup: "Purchase Request Management", name: "Purchase Request Validation", desc: "Validate request completeness, specifications, and required approvals." },
  { odId: "BPC-1274", group: "Procurement", subgroup: "Purchase Request Management", name: "Purchase Request Prioritization", desc: "Prioritize requests based on urgency, budget, and operational need." },
  { odId: "BPC-1275", group: "Procurement", subgroup: "Purchase Request Management", name: "Purchase Request Approval Routing", desc: "Route purchase request to procurement, finance, or approver according to workflow." },
  { odId: "BPC-1276", group: "Procurement", subgroup: "Sourcing", name: "Supplier Search", desc: "Identify potential suppliers for requested goods or services." },
  { odId: "BPC-1277", group: "Procurement", subgroup: "Sourcing", name: "Supplier Pre-Qualification", desc: "Assess supplier capability, legitimacy, and basic suitability." },
  { odId: "BPC-1278", group: "Procurement", subgroup: "Sourcing", name: "Quotation Request", desc: "Request quotation or proposal from supplier." },
  { odId: "BPC-1279", group: "Procurement", subgroup: "Sourcing", name: "Quotation Comparison", desc: "Compare supplier offers based on price, scope, quality, terms, and risk." },
  { odId: "BPC-1280", group: "Procurement", subgroup: "Sourcing", name: "Supplier Selection", desc: "Select supplier based on evaluation and approval." },
  { odId: "BPC-1281", group: "Procurement", subgroup: "Sourcing", name: "Sourcing Recommendation", desc: "Prepare sourcing recommendation for approval." },
  { odId: "BPC-1282", group: "Procurement", subgroup: "Purchase Order Management", name: "Purchase Order Preparation", desc: "Prepare purchase order based on approved request and supplier quotation." },
  { odId: "BPC-1283", group: "Procurement", subgroup: "Purchase Order Management", name: "Purchase Order Review", desc: "Review PO details, pricing, terms, and approval status." },
  { odId: "BPC-1284", group: "Procurement", subgroup: "Purchase Order Management", name: "Purchase Order Approval", desc: "Obtain required approval for purchase order." },
  { odId: "BPC-1285", group: "Procurement", subgroup: "Purchase Order Management", name: "Purchase Order Issuance", desc: "Issue approved purchase order to supplier." },
  { odId: "BPC-1286", group: "Procurement", subgroup: "Purchase Order Management", name: "Purchase Order Amendment", desc: "Update purchase order due to approved change." },
  { odId: "BPC-1287", group: "Procurement", subgroup: "Purchase Order Management", name: "Purchase Order Closure", desc: "Close purchase order after fulfillment and invoice processing." },
  { odId: "BPC-1288", group: "Procurement", subgroup: "Supplier Management", name: "Supplier Registration", desc: "Register supplier profile and supporting documents." },
  { odId: "BPC-1289", group: "Procurement", subgroup: "Supplier Management", name: "Supplier Evaluation", desc: "Evaluate supplier performance, capability, and risk." },
  { odId: "BPC-1290", group: "Procurement", subgroup: "Supplier Management", name: "Supplier Approval", desc: "Approve supplier for use based on evaluation result." },
  { odId: "BPC-1291", group: "Procurement", subgroup: "Supplier Management", name: "Supplier Performance Monitoring", desc: "Monitor delivery, quality, responsiveness, and issue history." },
  { odId: "BPC-1292", group: "Procurement", subgroup: "Supplier Management", name: "Supplier Review", desc: "Conduct periodic supplier review." },
  { odId: "BPC-1293", group: "Procurement", subgroup: "Supplier Management", name: "Supplier Corrective Action", desc: "Request supplier improvement or corrective action." },
  { odId: "BPC-1294", group: "Procurement", subgroup: "Supplier Management", name: "Supplier Offboarding", desc: "Deactivate or remove supplier from approved list." },
  { odId: "BPC-1295", group: "Procurement", subgroup: "Contract & Purchasing Administration", name: "Procurement Contract Review", desc: "Review purchasing terms, contract, agreement, or order conditions." },
  { odId: "BPC-1296", group: "Procurement", subgroup: "Contract & Purchasing Administration", name: "Procurement Document Control", desc: "Maintain procurement documents, quotations, approvals, and contracts." },
  { odId: "BPC-1297", group: "Procurement", subgroup: "Contract & Purchasing Administration", name: "Delivery Follow-up", desc: "Follow up supplier delivery or service completion." },
  { odId: "BPC-1298", group: "Procurement", subgroup: "Contract & Purchasing Administration", name: "Goods or Service Receipt Coordination", desc: "Coordinate receipt confirmation with requesting user." },
  { odId: "BPC-1299", group: "Procurement", subgroup: "Contract & Purchasing Administration", name: "Procurement Issue Resolution", desc: "Resolve procurement disputes, delays, mismatches, or supplier issues." },
  { odId: "BPC-1300", group: "Procurement", subgroup: "Contract & Purchasing Administration", name: "Procurement Reporting", desc: "Report procurement activity, spending, supplier status, and open requests." },
  { odId: "BPC-1301", group: "Software Development", subgroup: "Product Management", name: "Product Requirement Management", desc: "Capture, prioritize, and maintain product or system requirements." },
  { odId: "BPC-1302", group: "Software Development", subgroup: "Product Management", name: "Product Roadmap Planning", desc: "Plan product direction, feature priorities, and release timeline." },
  { odId: "BPC-1303", group: "Software Development", subgroup: "Product Management", name: "Backlog Management", desc: "Maintain backlog items, priorities, and refinement status." },
  { odId: "BPC-1304", group: "Software Development", subgroup: "Product Management", name: "User Story Definition", desc: "Define user stories, acceptance criteria, and expected outcomes." },
  { odId: "BPC-1305", group: "Software Development", subgroup: "Product Management", name: "Feature Prioritization", desc: "Prioritize features based on business value, risk, and effort." },
  { odId: "BPC-1306", group: "Software Development", subgroup: "Product Management", name: "Product Review", desc: "Review product performance, issues, and improvement opportunities." },
  { odId: "BPC-1307", group: "Software Development", subgroup: "Business Analysis", name: "Business Requirement Analysis", desc: "Analyze business needs, process flow, and stakeholder expectations." },
  { odId: "BPC-1308", group: "Software Development", subgroup: "Business Analysis", name: "Functional Requirement Definition", desc: "Define functional requirements for software solution." },
  { odId: "BPC-1309", group: "Software Development", subgroup: "Business Analysis", name: "Process Mapping", desc: "Map current and target business process flow." },
  { odId: "BPC-1310", group: "Software Development", subgroup: "Business Analysis", name: "Requirement Validation", desc: "Validate requirements with users, stakeholders, or product owner." },
  { odId: "BPC-1311", group: "Software Development", subgroup: "Business Analysis", name: "Change Request Analysis", desc: "Analyze requested changes and their impact." },
  { odId: "BPC-1312", group: "Software Development", subgroup: "Business Analysis", name: "Acceptance Criteria Definition", desc: "Define criteria used to confirm completion of requirement." },
  { odId: "BPC-1313", group: "Software Development", subgroup: "Software Design", name: "System Design", desc: "Design system structure, components, and behavior." },
  { odId: "BPC-1314", group: "Software Development", subgroup: "Software Design", name: "User Interface Design", desc: "Design user interface, layout, and interaction flow." },
  { odId: "BPC-1315", group: "Software Development", subgroup: "Software Design", name: "Database Design", desc: "Design data model, tables, relationships, and data rules." },
  { odId: "BPC-1316", group: "Software Development", subgroup: "Software Design", name: "API Design", desc: "Define API endpoints, payloads, authentication, and integration behavior." },
  { odId: "BPC-1317", group: "Software Development", subgroup: "Software Design", name: "Architecture Review", desc: "Review software architecture for maintainability, scalability, and security." },
  { odId: "BPC-1318", group: "Software Development", subgroup: "Software Design", name: "Technical Specification Preparation", desc: "Prepare technical specifications for development." },
  { odId: "BPC-1319", group: "Software Development", subgroup: "Development", name: "Frontend Development", desc: "Build user interface and client-side application features." },
  { odId: "BPC-1320", group: "Software Development", subgroup: "Development", name: "Backend Development", desc: "Build server-side logic, APIs, and application services." },
  { odId: "BPC-1321", group: "Software Development", subgroup: "Development", name: "Database Development", desc: "Create or update database schema, queries, and data processing logic." },
  { odId: "BPC-1322", group: "Software Development", subgroup: "Development", name: "Integration Development", desc: "Build integration with internal or external systems." },
  { odId: "BPC-1323", group: "Software Development", subgroup: "Development", name: "Code Review", desc: "Review source code for quality, maintainability, and security." },
  { odId: "BPC-1324", group: "Software Development", subgroup: "Development", name: "Version Control Management", desc: "Manage source code branches, commits, merges, and releases." },
  { odId: "BPC-1325", group: "Software Development", subgroup: "Quality Assurance", name: "Test Planning", desc: "Define test approach, scope, cases, data, and responsibilities." },
  { odId: "BPC-1326", group: "Software Development", subgroup: "Quality Assurance", name: "Functional Testing", desc: "Test whether features work according to requirements." },
  { odId: "BPC-1327", group: "Software Development", subgroup: "Quality Assurance", name: "Regression Testing", desc: "Test existing functionality after changes." },
  { odId: "BPC-1328", group: "Software Development", subgroup: "Quality Assurance", name: "User Acceptance Testing Support", desc: "Support user acceptance testing and issue resolution." },
  { odId: "BPC-1329", group: "Software Development", subgroup: "Quality Assurance", name: "Defect Management", desc: "Record, prioritize, assign, and verify software defects." },
  { odId: "BPC-1330", group: "Software Development", subgroup: "Quality Assurance", name: "Test Result Reporting", desc: "Report testing results, defects, risks, and readiness." },
  { odId: "BPC-1331", group: "Software Development", subgroup: "Release Management", name: "Release Planning", desc: "Plan release scope, schedule, dependencies, and approval." },
  { odId: "BPC-1332", group: "Software Development", subgroup: "Release Management", name: "Build Preparation", desc: "Prepare application build or release package." },
  { odId: "BPC-1333", group: "Software Development", subgroup: "Release Management", name: "Deployment Readiness Review", desc: "Review readiness before deployment." },
  { odId: "BPC-1334", group: "Software Development", subgroup: "Release Management", name: "Release Approval", desc: "Obtain approval before production release." },
  { odId: "BPC-1335", group: "Software Development", subgroup: "Release Management", name: "Production Deployment", desc: "Deploy approved software release to production." },
  { odId: "BPC-1336", group: "Software Development", subgroup: "Release Management", name: "Post-Release Verification", desc: "Verify deployment outcome and system behavior." },
  { odId: "BPC-1337", group: "Software Development", subgroup: "Release Management", name: "Rollback Management", desc: "Execute rollback plan if release fails." },
  { odId: "BPC-1338", group: "Software Development", subgroup: "Secure Development", name: "Secure Coding", desc: "Apply secure coding practices during development." },
  { odId: "BPC-1339", group: "Software Development", subgroup: "Secure Development", name: "Security Requirement Review", desc: "Review security requirements for features or changes." },
  { odId: "BPC-1340", group: "Software Development", subgroup: "Secure Development", name: "Application Security Testing", desc: "Perform security testing on application or code." },
  { odId: "BPC-1341", group: "Software Development", subgroup: "Secure Development", name: "Vulnerability Remediation", desc: "Fix identified software vulnerabilities." },
  { odId: "BPC-1342", group: "Software Development", subgroup: "Secure Development", name: "Dependency Review", desc: "Review software libraries and dependencies for risk." },
  { odId: "BPC-1343", group: "Software Development", subgroup: "Secure Development", name: "Secrets Management", desc: "Manage application secrets, keys, and credentials securely." },
  { odId: "BPC-1344", group: "IT Operations", subgroup: "IT Service Desk", name: "IT Support Request Handling", desc: "Receive and resolve user IT support requests." },
  { odId: "BPC-1345", group: "IT Operations", subgroup: "IT Service Desk", name: "Incident Ticket Management", desc: "Record, categorize, prioritize, and resolve IT incidents." },
  { odId: "BPC-1346", group: "IT Operations", subgroup: "IT Service Desk", name: "Service Request Fulfillment", desc: "Fulfill standard IT service requests." },
  { odId: "BPC-1347", group: "IT Operations", subgroup: "IT Service Desk", name: "User Communication", desc: "Communicate IT ticket status, resolution, or workaround." },
  { odId: "BPC-1348", group: "IT Operations", subgroup: "IT Service Desk", name: "Escalation Management", desc: "Escalate unresolved or complex IT issues to relevant support level." },
  { odId: "BPC-1349", group: "IT Operations", subgroup: "IT Service Desk", name: "Knowledge Base Management", desc: "Maintain support articles, FAQs, and troubleshooting guides." },
  { odId: "BPC-1350", group: "IT Operations", subgroup: "Infrastructure Operations", name: "Server Administration", desc: "Manage servers, operating systems, and infrastructure configuration." },
  { odId: "BPC-1351", group: "IT Operations", subgroup: "Infrastructure Operations", name: "Network Administration", desc: "Manage network connectivity, devices, and configuration." },
  { odId: "BPC-1352", group: "IT Operations", subgroup: "Infrastructure Operations", name: "Cloud Operations", desc: "Manage cloud services, resources, accounts, and configurations." },
  { odId: "BPC-1353", group: "IT Operations", subgroup: "Infrastructure Operations", name: "Endpoint Management", desc: "Manage user devices, endpoint configuration, and lifecycle." },
  { odId: "BPC-1354", group: "IT Operations", subgroup: "Infrastructure Operations", name: "System Monitoring", desc: "Monitor system performance, availability, and alerts." },
  { odId: "BPC-1355", group: "IT Operations", subgroup: "Infrastructure Operations", name: "Capacity Monitoring", desc: "Monitor capacity, utilization, and resource needs." },
  { odId: "BPC-1356", group: "IT Operations", subgroup: "Infrastructure Operations", name: "Backup Operations", desc: "Perform and monitor backup activities." },
  { odId: "BPC-1357", group: "IT Operations", subgroup: "Infrastructure Operations", name: "Restore Testing", desc: "Test restoration of backup data or systems." },
  { odId: "BPC-1358", group: "IT Operations", subgroup: "Access Management", name: "User Account Provisioning", desc: "Create user accounts and assign access rights." },
  { odId: "BPC-1359", group: "IT Operations", subgroup: "Access Management", name: "User Account Modification", desc: "Modify access based on role or employment change." },
  { odId: "BPC-1360", group: "IT Operations", subgroup: "Access Management", name: "User Account Deprovisioning", desc: "Disable or remove access after termination or change." },
  { odId: "BPC-1361", group: "IT Operations", subgroup: "Access Management", name: "Access Request Review", desc: "Review access request against authorization rules." },
  { odId: "BPC-1362", group: "IT Operations", subgroup: "Access Management", name: "Privileged Access Management", desc: "Control privileged accounts and administrative access." },
  { odId: "BPC-1363", group: "IT Operations", subgroup: "Access Management", name: "Periodic Access Review", desc: "Review user access rights periodically." },
  { odId: "BPC-1364", group: "IT Operations", subgroup: "Access Management", name: "Authentication Management", desc: "Manage authentication settings and related controls." },
  { odId: "BPC-1365", group: "IT Operations", subgroup: "Change & Configuration", name: "IT Change Request Management", desc: "Receive and assess IT change requests." },
  { odId: "BPC-1366", group: "IT Operations", subgroup: "Change & Configuration", name: "Change Impact Assessment", desc: "Assess impact, risk, and required approval for change." },
  { odId: "BPC-1367", group: "IT Operations", subgroup: "Change & Configuration", name: "Change Approval", desc: "Approve or reject IT changes based on authority and risk." },
  { odId: "BPC-1368", group: "IT Operations", subgroup: "Change & Configuration", name: "Change Implementation", desc: "Implement approved IT changes." },
  { odId: "BPC-1369", group: "IT Operations", subgroup: "Change & Configuration", name: "Post-Change Review", desc: "Review change result, issues, and rollback needs." },
  { odId: "BPC-1370", group: "IT Operations", subgroup: "Change & Configuration", name: "Configuration Management", desc: "Maintain configuration records for systems, services, and assets." },
  { odId: "BPC-1371", group: "IT Operations", subgroup: "Change & Configuration", name: "Asset Inventory Management", desc: "Maintain inventory of IT assets and associated information." },
  { odId: "BPC-1372", group: "IT Operations", subgroup: "Security Operations", name: "Security Alert Monitoring", desc: "Monitor security alerts and suspicious activity." },
  { odId: "BPC-1373", group: "IT Operations", subgroup: "Security Operations", name: "Security Incident Response", desc: "Respond to information security incidents." },
  { odId: "BPC-1374", group: "IT Operations", subgroup: "Security Operations", name: "Vulnerability Management", desc: "Identify, assess, prioritize, and remediate vulnerabilities." },
  { odId: "BPC-1375", group: "IT Operations", subgroup: "Security Operations", name: "Patch Management", desc: "Plan, test, deploy, and verify patches." },
  { odId: "BPC-1376", group: "IT Operations", subgroup: "Security Operations", name: "Malware Protection Management", desc: "Manage anti-malware or endpoint protection controls." },
  { odId: "BPC-1377", group: "IT Operations", subgroup: "Security Operations", name: "Logging Management", desc: "Collect, retain, and review logs." },
  { odId: "BPC-1378", group: "IT Operations", subgroup: "Security Operations", name: "Security Event Escalation", desc: "Escalate security events based on severity and impact." },
  { odId: "BPC-1379", group: "IT Operations", subgroup: "Security Operations", name: "Security Control Monitoring", desc: "Monitor operation of security controls." },
  { odId: "BPC-1380", group: "IT Operations", subgroup: "Continuity & Recovery", name: "IT Continuity Planning", desc: "Plan continuity arrangements for IT services." },
  { odId: "BPC-1381", group: "IT Operations", subgroup: "Continuity & Recovery", name: "Disaster Recovery Planning", desc: "Define disaster recovery strategy, roles, and procedures." },
  { odId: "BPC-1382", group: "IT Operations", subgroup: "Continuity & Recovery", name: "Recovery Testing", desc: "Test recovery procedures and restore capability." },
  { odId: "BPC-1383", group: "IT Operations", subgroup: "Continuity & Recovery", name: "Availability Monitoring", desc: "Monitor service availability and downtime." },
  { odId: "BPC-1384", group: "IT Operations", subgroup: "Continuity & Recovery", name: "Major Incident Coordination", desc: "Coordinate response for major IT service disruption." },
  { odId: "BPC-1385", group: "IT Operations", subgroup: "Continuity & Recovery", name: "Service Recovery Review", desc: "Review recovery performance and improvement needs." },
];
