// GENERATED FILE — do not edit by hand.
// Extracted programmatically from OD's ISRA_VULN_CSV (fe-vibes-new-od/app.html:20301) —
// the categorized dataset OD's own migration (_israVulnCsvV1, app.html:20799-20802) uses
// to REPLACE the entire Vulnerability Library. Deduplicated case-insensitively on the
// trimmed name via OD's own _tnorm normalizer, in source order, ids assigned sequentially
// VUL-0001... (same scheme as OD). Cross-checked against isra-vuln-control-map.csv's own
// "Vulnerability ID" column — every id/name/category triple in that CSV matches a row here
// exactly, confirming this is the same vuln vocabulary OD's knowledge map was built against.
// Regenerate from app.html if OD's vulnerability catalogue changes.

export interface IsraVulnSeedRow {
  id: string;
  name: string;
  category: string;
  description: string;
  status: string;
}

export const ISRA_VULN_LIBRARY_SEED: readonly IsraVulnSeedRow[] = [
  { id: "VUL-0001", name: "Unsupported hardware", category: "Hardware", description: "Hardware is no longer supported by its manufacturer or an authorized service provider.", status: "Active" },
  { id: "VUL-0002", name: "Outdated hardware architecture", category: "Hardware", description: "The equipment lacks capabilities required to support current security and operational requirements.", status: "Active" },
  { id: "VUL-0003", name: "Insufficient hardware capacity", category: "Hardware", description: "Available processing, memory, or storage capacity is insufficient for expected demand.", status: "Active" },
  { id: "VUL-0004", name: "Lack of hardware redundancy", category: "Hardware", description: "Critical equipment does not have an alternative component capable of maintaining service.", status: "Active" },
  { id: "VUL-0005", name: "Unverified hardware failover", category: "Hardware", description: "Redundant hardware has not been tested to confirm successful automatic or manual failover.", status: "Active" },
  { id: "VUL-0006", name: "Absence of hardware health monitoring", category: "Hardware", description: "Component condition, errors, and impending failures are not continuously monitored.", status: "Active" },
  { id: "VUL-0007", name: "Missing hardware failure alerts", category: "Hardware", description: "Relevant personnel are not promptly notified when equipment fails or degrades.", status: "Active" },
  { id: "VUL-0008", name: "Poor preventive hardware maintenance", category: "Hardware", description: "Equipment is not adequately maintained to reduce the likelihood of failure.", status: "Active" },
  { id: "VUL-0009", name: "Incomplete hardware maintenance records", category: "Hardware", description: "Evidence of equipment inspection, servicing, and repair is incomplete.", status: "Active" },
  { id: "VUL-0010", name: "Lack of critical spare parts", category: "Hardware", description: "Replacement components required to restore critical equipment are not readily available.", status: "Active" },
  { id: "VUL-0011", name: "Unverified hardware compatibility", category: "Hardware", description: "Equipment is deployed without confirming compatibility with connected systems and components.", status: "Active" },
  { id: "VUL-0012", name: "Unprotected BIOS or UEFI configuration", category: "Hardware", description: "System firmware settings can be accessed or modified without adequate protection.", status: "Active" },
  { id: "VUL-0013", name: "Uncontrolled use of default firmware credentials", category: "Hardware", description: "Manufacturer-supplied firmware credentials remain active or usable.", status: "Active" },
  { id: "VUL-0014", name: "Outdated device firmware", category: "Hardware", description: "Equipment operates using firmware that lacks current security or reliability updates.", status: "Active" },
  { id: "VUL-0015", name: "Unverified firmware updates", category: "Hardware", description: "Equipment accepts firmware updates without sufficiently validating their origin and integrity.", status: "Active" },
  { id: "VUL-0016", name: "Absence of secure boot", category: "Hardware", description: "Equipment can start using unauthorized or modified boot components.", status: "Active" },
  { id: "VUL-0017", name: "Lack of hardware-based cryptographic protection", category: "Hardware", description: "Sensitive cryptographic operations are performed without suitable dedicated hardware protection.", status: "Active" },
  { id: "VUL-0018", name: "Uncontrolled use of disabled hardware security functions", category: "Hardware", description: "Available hardware-based protections such as secure enclaves or trusted platform modules are not enabled.", status: "Active" },
  { id: "VUL-0019", name: "Unprotected storage media", category: "Hardware", description: "Information stored on physical media lacks adequate protection against unauthorized access.", status: "Active" },
  { id: "VUL-0020", name: "Uncontrolled removable media ports", category: "Hardware", description: "External storage devices can be connected without authorization or technical restriction.", status: "Active" },
  { id: "VUL-0021", name: "Unrestricted physical communication ports", category: "Hardware", description: "Unnecessary physical network, serial, or peripheral ports remain available for use.", status: "Active" },
  { id: "VUL-0022", name: "Unprotected administrative console ports", category: "Hardware", description: "Administrative console interfaces can be physically accessed without adequate restriction.", status: "Active" },
  { id: "VUL-0023", name: "Inadequate equipment tamper protection", category: "Hardware", description: "Equipment can be opened, altered, or interfered with without detection.", status: "Active" },
  { id: "VUL-0024", name: "Absence of hardware tamper detection", category: "Hardware", description: "The organization cannot identify when protected equipment has been physically manipulated.", status: "Active" },
  { id: "VUL-0025", name: "Unprotected portable devices", category: "Hardware", description: "Portable equipment lacks adequate physical protection against theft or unauthorized removal.", status: "Active" },
  { id: "VUL-0026", name: "Uncontrolled placement of equipment in public areas", category: "Hardware", description: "Sensitive equipment is located where unauthorized persons can physically reach it.", status: "Active" },
  { id: "VUL-0027", name: "Unprotected server racks", category: "Hardware", description: "Servers, network devices, or storage equipment are housed in unlocked or inadequately secured racks.", status: "Active" },
  { id: "VUL-0028", name: "Inadequate security of equipment rooms", category: "Hardware", description: "Physical controls do not sufficiently restrict access to rooms containing critical equipment.", status: "Active" },
  { id: "VUL-0029", name: "Lack of physical access-control redundancy", category: "Hardware", description: "Failure of one physical access-control component can prevent authorized access or permit uncontrolled entry.", status: "Active" },
  { id: "VUL-0030", name: "Uncontrolled visitor access to equipment areas", category: "Hardware", description: "Visitors can enter sensitive equipment areas without adequate barriers or supervision.", status: "Active" },
  { id: "VUL-0031", name: "Insufficient physical surveillance coverage", category: "Hardware", description: "Sensitive equipment areas are not adequately covered by surveillance or equivalent monitoring.", status: "Active" },
  { id: "VUL-0032", name: "Absence of physical security alarms", category: "Hardware", description: "Unauthorized entry or equipment interference may occur without generating an alarm.", status: "Active" },
  { id: "VUL-0033", name: "Unmonitored physical security alarms", category: "Hardware", description: "Physical security alarms may activate without timely review or response.", status: "Active" },
  { id: "VUL-0034", name: "Susceptible to water exposure", category: "Hardware", description: "Equipment is installed without adequate protection from leaks, flooding, or water discharge.", status: "Active" },
  { id: "VUL-0035", name: "Susceptible to fire damage", category: "Hardware", description: "Critical equipment lacks adequate protection against fire and related heat or smoke.", status: "Active" },
  { id: "VUL-0036", name: "Inadequate fire detection", category: "Hardware", description: "A fire affecting equipment or facilities may not be detected promptly.", status: "Active" },
  { id: "VUL-0037", name: "Inadequate fire suppression", category: "Hardware", description: "Available fire-suppression arrangements may not adequately protect critical equipment.", status: "Active" },
  { id: "VUL-0038", name: "Absence of environmental temperature monitoring", category: "Hardware", description: "Unsafe equipment temperatures may not be detected promptly.", status: "Active" },
  { id: "VUL-0039", name: "Absence of environmental humidity monitoring", category: "Hardware", description: "Unsafe humidity conditions may not be detected promptly.", status: "Active" },
  { id: "VUL-0040", name: "Insufficient cooling capacity", category: "Hardware", description: "Cooling equipment cannot reliably maintain safe operating conditions.", status: "Active" },
  { id: "VUL-0041", name: "Lack of cooling-system redundancy", category: "Hardware", description: "Failure of one cooling component can disrupt critical equipment.", status: "Active" },
  { id: "VUL-0042", name: "Absence of uninterruptible power supply", category: "Hardware", description: "Critical equipment cannot continue operating during a short power interruption.", status: "Active" },
  { id: "VUL-0043", name: "Insufficient backup power capacity", category: "Hardware", description: "Alternative power cannot support critical equipment for the required duration.", status: "Active" },
  { id: "VUL-0044", name: "Inadequate power conditioning", category: "Hardware", description: "Equipment is not sufficiently protected against voltage fluctuations and electrical disturbances.", status: "Active" },
  { id: "VUL-0045", name: "Lack of power-supply redundancy", category: "Hardware", description: "Critical equipment relies on a single power source or supply component.", status: "Active" },
  { id: "VUL-0046", name: "Unprotected communication cables", category: "Hardware", description: "Network and communication cables can be accessed, damaged, or tapped without authorization.", status: "Active" },
  { id: "VUL-0047", name: "Unprotected power cables", category: "Hardware", description: "Power connections can be disconnected, damaged, or manipulated without authorization.", status: "Active" },
  { id: "VUL-0048", name: "Uncontrolled hardware disposal", category: "Hardware", description: "Equipment may be discarded without authorization, tracking, or appropriate protection.", status: "Active" },
  { id: "VUL-0049", name: "Inadequate storage media sanitization", category: "Hardware", description: "Information may remain recoverable after media is reused, transferred, or disposed of.", status: "Active" },
  { id: "VUL-0050", name: "Failure to securely destroy damaged media", category: "Hardware", description: "Damaged or unreadable media may retain recoverable sensitive information.", status: "Active" },
  { id: "VUL-0051", name: "Incomplete hardware location records", category: "Hardware", description: "The current physical location of equipment cannot be reliably determined.", status: "Active" },
  { id: "VUL-0052", name: "Uncontrolled equipment movement", category: "Hardware", description: "Hardware can be relocated without approval, tracking, or verification.", status: "Active" },
  { id: "VUL-0053", name: "Unclear hardware ownership", category: "Hardware", description: "Equipment lacks a clearly identified responsible owner or custodian.", status: "Active" },
  { id: "VUL-0054", name: "Uncontrolled connection of unauthorized devices", category: "Hardware", description: "Unapproved equipment can be physically connected to organizational infrastructure.", status: "Active" },
  { id: "VUL-0055", name: "Unrestricted device reset functions", category: "Hardware", description: "Equipment can be reset to an insecure or default state without authorization.", status: "Active" },
  { id: "VUL-0056", name: "Unprotected hardware diagnostic interfaces", category: "Hardware", description: "Diagnostic and maintenance interfaces can be used without adequate authorization.", status: "Active" },
  { id: "VUL-0057", name: "Poor equipment installation", category: "Hardware", description: "Equipment is installed in a manner that increases the likelihood of damage, failure, or unauthorized access.", status: "Active" },
  { id: "VUL-0058", name: "Unsupported software", category: "Software", description: "Software is no longer supported by its vendor or development community.", status: "Active" },
  { id: "VUL-0059", name: "Unsupported operating system", category: "Software", description: "An operating system remains in use after security support has ended.", status: "Active" },
  { id: "VUL-0060", name: "Missing security patches", category: "Software", description: "Available security updates have not been installed.", status: "Active" },
  { id: "VUL-0061", name: "Outdated software components", category: "Software", description: "Applications use components that lack current security or reliability updates.", status: "Active" },
  { id: "VUL-0062", name: "Incomplete software inventory", category: "Software", description: "The organization cannot reliably identify all software and versions currently deployed.", status: "Active" },
  { id: "VUL-0063", name: "Insecure default software configuration", category: "Software", description: "Software operates using insecure vendor-supplied or initial settings.", status: "Active" },
  { id: "VUL-0064", name: "Uncontrolled software functionality", category: "Software", description: "Functions without an approved operational need remain enabled.", status: "Active" },
  { id: "VUL-0065", name: "Uncontrolled software services", category: "Software", description: "Software services without an approved business need remain active.", status: "Active" },
  { id: "VUL-0066", name: "Uncontrolled debug functionality in production", category: "Software", description: "Production software exposes diagnostic functions intended for development or testing.", status: "Active" },
  { id: "VUL-0067", name: "Excessive information in error messages", category: "Software", description: "Application errors reveal unnecessary technical, personal, or security-relevant information.", status: "Active" },
  { id: "VUL-0068", name: "Unprotected administrative interfaces", category: "Software", description: "Software administration functions are exposed without adequate access restrictions.", status: "Active" },
  { id: "VUL-0069", name: "Failure to change default software credentials", category: "Software", description: "Manufacturer or developer-supplied credentials remain active.", status: "Active" },
  { id: "VUL-0070", name: "Weak password requirements", category: "Software", description: "Software permits passwords that provide insufficient resistance to compromise.", status: "Active" },
  { id: "VUL-0071", name: "Absence of multi-factor authentication", category: "Software", description: "Software permits access using only one authentication factor where stronger authentication is required.", status: "Active" },
  { id: "VUL-0072", name: "Weak multi-factor authentication configuration", category: "Software", description: "Implemented multi-factor authentication can be bypassed or provides insufficient assurance.", status: "Active" },
  { id: "VUL-0073", name: "Missing account lockout controls", category: "Software", description: "Repeated failed authentication attempts do not trigger an appropriate restriction.", status: "Active" },
  { id: "VUL-0074", name: "Insufficient brute-force protection", category: "Software", description: "Software does not adequately slow, block, or detect repeated authentication attempts.", status: "Active" },
  { id: "VUL-0075", name: "Insecure password storage", category: "Software", description: "Passwords are stored using inadequate cryptographic protection.", status: "Active" },
  { id: "VUL-0076", name: "Unprotected plaintext credentials", category: "Software", description: "Authentication credentials are stored without adequate protection.", status: "Active" },
  { id: "VUL-0077", name: "Uncontrolled credentials in source code", category: "Software", description: "Authentication credentials are embedded directly within source code.", status: "Active" },
  { id: "VUL-0078", name: "Unprotected credentials in configuration files", category: "Software", description: "Authentication credentials are stored in configuration files without adequate safeguards.", status: "Active" },
  { id: "VUL-0079", name: "Excessive credential validity periods", category: "Software", description: "Credentials remain valid longer than required for their intended purpose.", status: "Active" },
  { id: "VUL-0080", name: "Inadequate credential rotation", category: "Software", description: "Credentials are not changed at appropriate intervals or after relevant events.", status: "Active" },
  { id: "VUL-0081", name: "Inadequate credential revocation", category: "Software", description: "Compromised, expired, or unnecessary credentials cannot be invalidated promptly.", status: "Active" },
  { id: "VUL-0082", name: "Insecure access-token storage", category: "Software", description: "Authentication or authorization tokens are stored where unauthorized parties may obtain them.", status: "Active" },
  { id: "VUL-0083", name: "Unprotected access tokens in URLs", category: "Software", description: "Sensitive tokens are included in URLs and may be recorded or disclosed.", status: "Active" },
  { id: "VUL-0084", name: "Excessive access-token validity periods", category: "Software", description: "Access tokens remain valid longer than necessary.", status: "Active" },
  { id: "VUL-0085", name: "Inadequate access-token revocation", category: "Software", description: "Access tokens cannot be invalidated promptly when no longer trusted.", status: "Active" },
  { id: "VUL-0086", name: "Insufficient access-token validation", category: "Software", description: "Software does not sufficiently verify token authenticity, issuer, scope, audience, or validity.", status: "Active" },
  { id: "VUL-0087", name: "Weak session identifiers", category: "Software", description: "Session identifiers can be guessed, predicted, or derived.", status: "Active" },
  { id: "VUL-0088", name: "Insecure session-cookie configuration", category: "Software", description: "Session cookies lack appropriate security attributes and restrictions.", status: "Active" },
  { id: "VUL-0089", name: "Excessive session duration", category: "Software", description: "Authenticated sessions remain active longer than necessary.", status: "Active" },
  { id: "VUL-0090", name: "Incomplete session invalidation", category: "Software", description: "Sessions remain usable after logout, password change, account suspension, or termination.", status: "Active" },
  { id: "VUL-0091", name: "Absence of reauthentication for sensitive actions", category: "Software", description: "High-risk functions can be performed without reconfirming the user's identity.", status: "Active" },
  { id: "VUL-0092", name: "Missing server-side authorization checks", category: "Software", description: "Access decisions are not adequately enforced by the server.", status: "Active" },
  { id: "VUL-0093", name: "Missing function-level authorization", category: "Software", description: "Restricted application functions can be invoked without appropriate permission checks.", status: "Active" },
  { id: "VUL-0094", name: "Inadequate record-level authorization", category: "Software", description: "Users can access records outside their authorized scope.", status: "Active" },
  { id: "VUL-0095", name: "Insecure direct object references", category: "Software", description: "Internal identifiers can be manipulated to access unauthorized resources.", status: "Active" },
  { id: "VUL-0096", name: "Inadequate tenant isolation", category: "Software", description: "Information or functions can cross between customers or tenants without authorization.", status: "Active" },
  { id: "VUL-0097", name: "Excessive application service-account privileges", category: "Software", description: "An application service account can perform more operations than required.", status: "Active" },
  { id: "VUL-0098", name: "Unprotected dynamic database queries", category: "Software", description: "Application input is incorporated into database queries without safe parameter handling.", status: "Active" },
  { id: "VUL-0099", name: "Insufficient server-side input validation", category: "Software", description: "Application input is not adequately validated before processing.", status: "Active" },
  { id: "VUL-0100", name: "Inadequate output encoding", category: "Software", description: "Application output is not safely encoded for its destination context.", status: "Active" },
  { id: "VUL-0101", name: "Insecure deserialization", category: "Software", description: "Untrusted serialized data can be processed in a manner that permits unauthorized behavior.", status: "Active" },
  { id: "VUL-0102", name: "Uncontrolled file uploads", category: "Software", description: "Software accepts files without sufficient type, size, content, or destination restrictions.", status: "Active" },
  { id: "VUL-0103", name: "Absence of cross-site request forgery protection", category: "Software", description: "State-changing requests can be initiated without adequately verifying user intent.", status: "Active" },
  { id: "VUL-0104", name: "Incorrect cross-origin resource-sharing configuration", category: "Software", description: "Cross-origin access is permitted more broadly than required.", status: "Active" },
  { id: "VUL-0105", name: "Missing browser security headers", category: "Software", description: "Application responses omit relevant browser security directives.", status: "Active" },
  { id: "VUL-0106", name: "Uncontrolled open redirect functionality", category: "Software", description: "User-controlled input can redirect users to an untrusted destination.", status: "Active" },
  { id: "VUL-0107", name: "Insufficient business-logic validation", category: "Software", description: "Software does not adequately enforce intended business rules and transaction sequences.", status: "Active" },
  { id: "VUL-0108", name: "Inadequate transaction validation", category: "Software", description: "Transactions are processed without adequate validation of their content, context, and authorization.", status: "Active" },
  { id: "VUL-0109", name: "Absence of replay protection", category: "Software", description: "Previously valid requests or transactions can be accepted repeatedly.", status: "Active" },
  { id: "VUL-0110", name: "Weak resource identifiers", category: "Software", description: "Application resource identifiers can be guessed or systematically enumerated.", status: "Active" },
  { id: "VUL-0111", name: "Insecure temporary file handling", category: "Software", description: "Temporary information is stored or retained without adequate protection.", status: "Active" },
  { id: "VUL-0112", name: "Unprotected sensitive data in application logs", category: "Software", description: "Application logging records confidential, personal, or authentication information.", status: "Active" },
  { id: "VUL-0113", name: "Unprotected sensitive data in error responses", category: "Software", description: "Application error responses reveal protected information.", status: "Active" },
  { id: "VUL-0114", name: "Insecure browser storage of sensitive data", category: "Software", description: "Protected information is retained in browser-accessible storage without adequate safeguards.", status: "Active" },
  { id: "VUL-0115", name: "Outdated application dependencies", category: "Software", description: "Applications rely on dependency versions that lack current security updates.", status: "Active" },
  { id: "VUL-0116", name: "Unverified software dependencies", category: "Software", description: "The origin and integrity of external software components are not adequately confirmed.", status: "Active" },
  { id: "VUL-0117", name: "Unverified third-party application components", category: "Software", description: "External components are introduced without appropriate security validation.", status: "Active" },
  { id: "VUL-0118", name: "Insufficient application security testing", category: "Software", description: "Software is released without adequate testing for relevant security weaknesses.", status: "Active" },
  { id: "VUL-0119", name: "Absence of static application security testing", category: "Software", description: "Source or compiled code is not systematically analyzed for security weaknesses.", status: "Active" },
  { id: "VUL-0120", name: "Absence of dynamic application security testing", category: "Software", description: "Running applications are not systematically tested for exploitable weaknesses.", status: "Active" },
  { id: "VUL-0121", name: "Absence of software composition analysis", category: "Software", description: "Third-party components and their known vulnerabilities are not systematically identified.", status: "Active" },
  { id: "VUL-0122", name: "Poor source-code review", category: "Software", description: "Software changes are accepted without sufficient independent security review.", status: "Active" },
  { id: "VUL-0123", name: "Missing branch protection", category: "Software", description: "Protected source-code branches can be changed without required reviews or controls.", status: "Active" },
  { id: "VUL-0124", name: "Insufficient pull-request approval", category: "Software", description: "Source-code changes can be merged without appropriate independent approval.", status: "Active" },
  { id: "VUL-0125", name: "Excessive source-code repository permissions", category: "Software", description: "Repository users have broader access than required.", status: "Active" },
  { id: "VUL-0126", name: "Unprotected public source-code repository", category: "Software", description: "Restricted source code is accessible publicly.", status: "Active" },
  { id: "VUL-0127", name: "Unclear attribution of source-code changes", category: "Software", description: "Changes cannot be reliably linked to an identified person or process.", status: "Active" },
  { id: "VUL-0128", name: "Unverified third-party build actions", category: "Software", description: "Externally sourced build actions execute without appropriate validation.", status: "Active" },
  { id: "VUL-0129", name: "Inadequate build-runner isolation", category: "Software", description: "Build jobs can improperly affect other jobs, systems, or environments.", status: "Active" },
  { id: "VUL-0130", name: "Unprotected pipeline secrets", category: "Software", description: "Build or deployment credentials are stored without adequate protection.", status: "Active" },
  { id: "VUL-0131", name: "Unprotected sensitive values in build logs", category: "Software", description: "Build or deployment logs reveal credentials or protected information.", status: "Active" },
  { id: "VUL-0132", name: "Excessive pipeline permissions", category: "Software", description: "Build and deployment processes have more privileges than required.", status: "Active" },
  { id: "VUL-0133", name: "Absence of digital signatures for build artifacts", category: "Software", description: "Software artifacts lack verifiable evidence of origin and integrity.", status: "Active" },
  { id: "VUL-0134", name: "Unverified artifact integrity", category: "Software", description: "Software artifacts are accepted without confirming that they are authentic and unchanged.", status: "Active" },
  { id: "VUL-0135", name: "Excessive artifact-repository permissions", category: "Software", description: "Users or services have broader artifact access than required.", status: "Active" },
  { id: "VUL-0136", name: "Inadequate deployment approval", category: "Software", description: "Software can be deployed without appropriate authorization.", status: "Active" },
  { id: "VUL-0137", name: "Unrestricted developer access to production", category: "Software", description: "Development personnel can access or change production environments beyond operational need.", status: "Active" },
  { id: "VUL-0138", name: "Inadequate separation of development and production", category: "Software", description: "Development activity can directly affect production systems or information.", status: "Active" },
  { id: "VUL-0139", name: "Uncontrolled use of production data in testing", category: "Software", description: "Live organizational information is copied into less-controlled test environments.", status: "Active" },
  { id: "VUL-0140", name: "Weak API authentication", category: "Software", description: "API clients are authenticated using methods that provide insufficient assurance.", status: "Active" },
  { id: "VUL-0141", name: "Insufficient API authorization validation", category: "Software", description: "API operations do not adequately verify the caller's permissions.", status: "Active" },
  { id: "VUL-0142", name: "Inadequate API token management", category: "Software", description: "API credentials are not securely issued, stored, scoped, rotated, or revoked.", status: "Active" },
  { id: "VUL-0143", name: "Absence of API rate limiting", category: "Software", description: "API clients can submit requests without appropriate frequency or volume restrictions.", status: "Active" },
  { id: "VUL-0144", name: "Insufficient API input validation", category: "Software", description: "API request content is not adequately validated before processing.", status: "Active" },
  { id: "VUL-0145", name: "Inadequate API schema validation", category: "Software", description: "API requests and responses are not checked against an approved structure.", status: "Active" },
  { id: "VUL-0146", name: "Excessive data in API responses", category: "Software", description: "API responses include more information than required for the authorized purpose.", status: "Active" },
  { id: "VUL-0147", name: "Uncontrolled deprecated API versions", category: "Software", description: "Obsolete or unsupported API versions remain accessible.", status: "Active" },
  { id: "VUL-0148", name: "Insufficient API activity monitoring", category: "Software", description: "API usage is not adequately logged, reviewed, or analyzed.", status: "Active" },
  { id: "VUL-0149", name: "Inadequate webhook validation", category: "Software", description: "Webhook messages are accepted without sufficient source and integrity verification.", status: "Active" },
  { id: "VUL-0150", name: "Missing request-signature validation", category: "Software", description: "Signed requests are accepted without verifying the signature.", status: "Active" },
  { id: "VUL-0151", name: "Absence of API replay protection", category: "Software", description: "Previously valid API requests can be resubmitted and accepted.", status: "Active" },
  { id: "VUL-0152", name: "Unprotected data at rest", category: "Software", description: "Stored information lacks required cryptographic protection.", status: "Active" },
  { id: "VUL-0153", name: "Unprotected data in transit", category: "Software", description: "Information transmitted between systems lacks required cryptographic protection.", status: "Active" },
  { id: "VUL-0154", name: "Weak cryptographic algorithms", category: "Software", description: "Software relies on algorithms that no longer provide sufficient protection.", status: "Active" },
  { id: "VUL-0155", name: "Outdated cryptographic protocols", category: "Software", description: "Software accepts obsolete or insecure cryptographic protocols.", status: "Active" },
  { id: "VUL-0156", name: "Insecure cryptographic-key storage", category: "Software", description: "Cryptographic keys are stored without adequate protection or separation.", status: "Active" },
  { id: "VUL-0157", name: "Unprotected hard-coded cryptographic keys", category: "Software", description: "Cryptographic keys are embedded directly within software or configuration.", status: "Active" },
  { id: "VUL-0158", name: "Inadequate cryptographic-key rotation", category: "Software", description: "Keys are not replaced at appropriate intervals or after relevant events.", status: "Active" },
  { id: "VUL-0159", name: "Inadequate cryptographic-key revocation", category: "Software", description: "Compromised or obsolete keys cannot be invalidated promptly.", status: "Active" },
  { id: "VUL-0160", name: "Insufficient certificate validation", category: "Software", description: "Software does not properly verify certificate identity, validity, and trust.", status: "Active" },
  { id: "VUL-0161", name: "Outdated digital certificates", category: "Software", description: "Software relies on certificates that are expired or no longer appropriate.", status: "Active" },
  { id: "VUL-0162", name: "Insufficient security logging", category: "Software", description: "Software does not record enough information for monitoring, investigation, and accountability.", status: "Active" },
  { id: "VUL-0163", name: "Unprotected security logs", category: "Software", description: "Software-generated logs can be modified or deleted without authorization.", status: "Active" },
  { id: "VUL-0164", name: "Incomplete audit trails", category: "Software", description: "Software does not retain a complete history of relevant activities and changes.", status: "Active" },
  { id: "VUL-0165", name: "Incorrect system time synchronization", category: "Software", description: "Software records activities using inaccurate or inconsistent time references.", status: "Active" },
  { id: "VUL-0166", name: "Missing security alerts", category: "Software", description: "Relevant software events do not produce timely notifications.", status: "Active" },
  { id: "VUL-0167", name: "Unprotected backup data", category: "Software", description: "Backup copies lack adequate access or cryptographic protection.", status: "Active" },
  { id: "VUL-0168", name: "Unverified backup integrity", category: "Software", description: "Backup copies are not checked for completeness and integrity.", status: "Active" },
  { id: "VUL-0169", name: "Absence of backup immutability", category: "Software", description: "Backup copies can be altered or deleted through ordinary administrative access.", status: "Active" },
  { id: "VUL-0170", name: "Unverified backup restoration", category: "Software", description: "The ability to restore usable information from backups has not been demonstrated.", status: "Active" },
  { id: "VUL-0171", name: "Uncontrolled shared database administrator accounts", category: "Software", description: "Multiple persons use the same database administrative identity.", status: "Active" },
  { id: "VUL-0172", name: "Excessive database service-account privileges", category: "Software", description: "Application database accounts can perform more operations than required.", status: "Active" },
  { id: "VUL-0173", name: "Insufficient database auditing", category: "Software", description: "Relevant database access and changes are not adequately recorded.", status: "Active" },
  { id: "VUL-0174", name: "Unprotected sensitive database fields", category: "Software", description: "Sensitive database content lacks appropriate cryptographic protection.", status: "Active" },
  { id: "VUL-0175", name: "Weak database connection authentication", category: "Software", description: "Connections to the database are accepted without adequate identity verification.", status: "Active" },
  { id: "VUL-0176", name: "Excessive database network exposure", category: "Software", description: "The database service is reachable from more locations than required.", status: "Active" },
  { id: "VUL-0177", name: "Inadequate network segmentation", category: "Network", description: "Systems with different security requirements are not sufficiently separated.", status: "Active" },
  { id: "VUL-0178", name: "Insufficient isolation of sensitive network zones", category: "Network", description: "High-value systems share network access with lower-trust assets.", status: "Active" },
  { id: "VUL-0179", name: "Excessive firewall permissions", category: "Network", description: "Firewall rules allow more traffic, sources, destinations, or services than required.", status: "Active" },
  { id: "VUL-0180", name: "Inadequate firewall rule review", category: "Network", description: "Obsolete or unnecessary firewall access remains undetected.", status: "Active" },
  { id: "VUL-0181", name: "Uncontrolled open network ports", category: "Network", description: "Network services are exposed without an approved operational requirement.", status: "Active" },
  { id: "VUL-0182", name: "Uncontrolled network services", category: "Network", description: "Network-facing services without an approved need remain active.", status: "Active" },
  { id: "VUL-0183", name: "Insecure network protocols", category: "Network", description: "Communications use protocols that lack adequate security protection.", status: "Active" },
  { id: "VUL-0184", name: "Unprotected network communication", category: "Network", description: "Sensitive information travels across networks without adequate encryption.", status: "Active" },
  { id: "VUL-0185", name: "Weak TLS configuration", category: "Network", description: "Encrypted network services permit weak protocols, algorithms, or configurations.", status: "Active" },
  { id: "VUL-0186", name: "Insecure remote administration", category: "Network", description: "Administrative network access lacks appropriate encryption, authentication, or restriction.", status: "Active" },
  { id: "VUL-0187", name: "Failure to change default network-device credentials", category: "Network", description: "Manufacturer-supplied credentials remain active on network equipment.", status: "Active" },
  { id: "VUL-0188", name: "Outdated network-device firmware", category: "Network", description: "Network equipment operates using firmware without current security updates.", status: "Active" },
  { id: "VUL-0189", name: "Missing network-device configuration backups", category: "Network", description: "Required network configurations cannot be reliably restored.", status: "Active" },
  { id: "VUL-0190", name: "Uncontrolled network-device configuration changes", category: "Network", description: "Network settings can be changed without appropriate authorization and review.", status: "Active" },
  { id: "VUL-0191", name: "Absence of network access control", category: "Network", description: "Devices can connect without adequate identity or compliance verification.", status: "Active" },
  { id: "VUL-0192", name: "Failure to detect unauthorized network devices", category: "Network", description: "Unapproved devices can remain connected without timely identification.", status: "Active" },
  { id: "VUL-0193", name: "Weak wireless encryption", category: "Network", description: "Wireless communications use outdated or inadequate protection.", status: "Active" },
  { id: "VUL-0194", name: "Weak wireless authentication", category: "Network", description: "Wireless access does not sufficiently verify user or device identity.", status: "Active" },
  { id: "VUL-0195", name: "Failure to detect rogue wireless access points", category: "Network", description: "Unauthorized wireless access points can operate without timely detection.", status: "Active" },
  { id: "VUL-0196", name: "Inadequate guest wireless isolation", category: "Network", description: "Guest devices can reach internal organizational resources.", status: "Active" },
  { id: "VUL-0197", name: "Excessive wireless signal coverage", category: "Network", description: "Wireless signals extend farther beyond controlled areas than necessary.", status: "Active" },
  { id: "VUL-0198", name: "Weak VPN authentication", category: "Network", description: "Remote network access does not sufficiently verify user or device identity.", status: "Active" },
  { id: "VUL-0199", name: "Excessive VPN access", category: "Network", description: "Remote users can reach more network resources than required.", status: "Active" },
  { id: "VUL-0200", name: "Uncontrolled split tunneling", category: "Network", description: "Remote devices can simultaneously connect to trusted and untrusted networks without adequate restriction.", status: "Active" },
  { id: "VUL-0201", name: "Inadequate DNS security configuration", category: "Network", description: "DNS services lack sufficient protection against unauthorized alteration or fraudulent responses.", status: "Active" },
  { id: "VUL-0202", name: "Absence of DNS change monitoring", category: "Network", description: "Unauthorized or erroneous DNS modifications may not be detected promptly.", status: "Active" },
  { id: "VUL-0203", name: "Incomplete email authentication controls", category: "Network", description: "Email domains do not fully implement appropriate sender-authentication mechanisms.", status: "Active" },
  { id: "VUL-0204", name: "Unprotected email transmission", category: "Network", description: "Email communications can be transmitted without adequate encryption.", status: "Active" },
  { id: "VUL-0205", name: "Insufficient email filtering", category: "Network", description: "Malicious or fraudulent messages are not adequately detected and blocked.", status: "Active" },
  { id: "VUL-0206", name: "Insufficient network traffic monitoring", category: "Network", description: "Relevant network activity is not adequately observed or analyzed.", status: "Active" },
  { id: "VUL-0207", name: "Uncontrolled encrypted network traffic", category: "Network", description: "Malicious activity within encrypted communications may pass without appropriate inspection.", status: "Active" },
  { id: "VUL-0208", name: "Insufficient network intrusion detection", category: "Network", description: "Potential intrusions are not detected or alerted promptly.", status: "Active" },
  { id: "VUL-0209", name: "Insufficient network intrusion prevention", category: "Network", description: "Known malicious network activity is not automatically restricted where appropriate.", status: "Active" },
  { id: "VUL-0210", name: "Inadequate denial-of-service protection", category: "Network", description: "Network services lack sufficient protection against traffic-based disruption.", status: "Active" },
  { id: "VUL-0211", name: "Insufficient network capacity monitoring", category: "Network", description: "Exhaustion or abnormal consumption of network capacity may not be identified promptly.", status: "Active" },
  { id: "VUL-0212", name: "Lack of network redundancy", category: "Network", description: "Failure of one network component or connection can interrupt critical services.", status: "Active" },
  { id: "VUL-0213", name: "Lack of internet connectivity redundancy", category: "Network", description: "Loss of one internet connection can interrupt required external connectivity.", status: "Active" },
  { id: "VUL-0214", name: "Unverified network failover", category: "Network", description: "Alternative network routes or connections have not been tested for successful operation.", status: "Active" },
  { id: "VUL-0215", name: "Uncontrolled routing changes", category: "Network", description: "Network routes can be altered without appropriate authorization and review.", status: "Active" },
  { id: "VUL-0216", name: "Insufficient routing activity monitoring", category: "Network", description: "Unauthorized or abnormal routing changes may not be detected.", status: "Active" },
  { id: "VUL-0217", name: "Outdated network architecture documentation", category: "Network", description: "Network diagrams and recorded connections do not reflect the current environment.", status: "Active" },
  { id: "VUL-0218", name: "Uncontrolled IPv6 traffic", category: "Network", description: "IPv6 connectivity operates without security controls equivalent to other network traffic.", status: "Active" },
  { id: "VUL-0219", name: "Insecure network-management protocol configuration", category: "Network", description: "Network-management communication uses weak credentials or insecure protocol versions.", status: "Active" },
  { id: "VUL-0220", name: "Unprotected network management interfaces", category: "Network", description: "Administrative interfaces are accessible from untrusted networks.", status: "Active" },
  { id: "VUL-0221", name: "Weak communication endpoint authentication", category: "Network", description: "Systems exchange information without adequately verifying the other endpoint.", status: "Active" },
  { id: "VUL-0222", name: "Absence of message-integrity verification", category: "Network", description: "Network messages can be altered without detection.", status: "Active" },
  { id: "VUL-0223", name: "Absence of network replay protection", category: "Network", description: "Previously transmitted messages can be resent and accepted as new.", status: "Active" },
  { id: "VUL-0224", name: "Inadequate isolation of third-party network connections", category: "Network", description: "External organizations connect to internal resources without sufficient separation.", status: "Active" },
  { id: "VUL-0225", name: "Excessive cloud network permissions", category: "Network", description: "Cloud security rules allow broader connectivity than required.", status: "Active" },
  { id: "VUL-0226", name: "Inadequate load balancer security configuration", category: "Network", description: "Traffic-management components do not apply appropriate security restrictions.", status: "Active" },
  { id: "VUL-0227", name: "Inadequate proxy security configuration", category: "Network", description: "Proxy services permit unsafe destinations, traffic, or bypass routes.", status: "Active" },
  { id: "VUL-0228", name: "Insufficient personnel security awareness", category: "Personnel", description: "Personnel lack adequate understanding of their information-security responsibilities.", status: "Active" },
  { id: "VUL-0229", name: "Insufficient phishing awareness", category: "Personnel", description: "Personnel are not adequately prepared to identify and respond to fraudulent communications.", status: "Active" },
  { id: "VUL-0230", name: "Inadequate role-specific security training", category: "Personnel", description: "Personnel have not received security training appropriate to their responsibilities.", status: "Active" },
  { id: "VUL-0231", name: "Insufficient technical security competence", category: "Personnel", description: "Personnel lack the technical knowledge required to perform security-relevant duties correctly.", status: "Active" },
  { id: "VUL-0232", name: "Failure to evaluate personnel competence", category: "Personnel", description: "The organization does not periodically verify that personnel meet required competence levels.", status: "Active" },
  { id: "VUL-0233", name: "Inadequate personnel screening", category: "Personnel", description: "Background or suitability checks do not reflect the sensitivity of assigned responsibilities.", status: "Active" },
  { id: "VUL-0234", name: "Unclear understanding of security responsibilities", category: "Personnel", description: "Personnel do not clearly understand the security obligations associated with their roles.", status: "Active" },
  { id: "VUL-0235", name: "Uncontrolled credential sharing", category: "Personnel", description: "Individuals disclose or reuse authentication credentials with other persons.", status: "Active" },
  { id: "VUL-0236", name: "Weak personnel password practices", category: "Personnel", description: "Individuals select passwords that provide insufficient resistance to compromise.", status: "Active" },
  { id: "VUL-0237", name: "Uncontrolled password reuse", category: "Personnel", description: "Individuals use the same or similar passwords across multiple services.", status: "Active" },
  { id: "VUL-0238", name: "Uncontrolled approval of authentication requests", category: "Personnel", description: "Personnel approve authentication prompts they did not initiate.", status: "Active" },
  { id: "VUL-0239", name: "Susceptible to social engineering", category: "Personnel", description: "Personnel are not adequately prepared to recognize manipulation or impersonation.", status: "Active" },
  { id: "VUL-0240", name: "Uncontrolled discussion of sensitive information", category: "Personnel", description: "Personnel discuss protected information where unauthorized persons may hear it.", status: "Active" },
  { id: "VUL-0241", name: "Unprotected sensitive information left unattended", category: "Personnel", description: "Personnel leave information or devices exposed without appropriate supervision.", status: "Active" },
  { id: "VUL-0242", name: "Poor clear-desk practices", category: "Personnel", description: "Sensitive documents or media remain exposed in work areas.", status: "Active" },
  { id: "VUL-0243", name: "Poor clear-screen practices", category: "Personnel", description: "Sensitive information remains visible on unattended or publicly observable screens.", status: "Active" },
  { id: "VUL-0244", name: "Failure to verify information recipients", category: "Personnel", description: "Personnel disclose or send information without adequately confirming the recipient.", status: "Active" },
  { id: "VUL-0245", name: "Incorrect selection of email attachments", category: "Personnel", description: "Personnel transmit the wrong protected information or document.", status: "Active" },
  { id: "VUL-0246", name: "Failure to report security incidents promptly", category: "Personnel", description: "Personnel delay or omit reporting of suspected security events.", status: "Active" },
  { id: "VUL-0247", name: "Failure to report suspicious communications", category: "Personnel", description: "Personnel do not promptly report suspected phishing or impersonation attempts.", status: "Active" },
  { id: "VUL-0248", name: "Uncontrolled bypass of security controls", category: "Personnel", description: "Personnel circumvent established controls to complete tasks more conveniently.", status: "Active" },
  { id: "VUL-0249", name: "Uncontrolled installation of software", category: "Personnel", description: "Personnel install applications without authorization or security review.", status: "Active" },
  { id: "VUL-0250", name: "Uncontrolled use of external cloud services", category: "Personnel", description: "Personnel store or process information using unapproved external services.", status: "Active" },
  { id: "VUL-0251", name: "Uncontrolled use of external AI services", category: "Personnel", description: "Personnel submit organizational information to unapproved artificial-intelligence services.", status: "Active" },
  { id: "VUL-0252", name: "Insecure use of removable media", category: "Personnel", description: "Personnel use portable storage without appropriate authorization or protection.", status: "Active" },
  { id: "VUL-0253", name: "Poor remote-working security practices", category: "Personnel", description: "Personnel working outside controlled premises do not adequately protect information and equipment.", status: "Active" },
  { id: "VUL-0254", name: "Uncontrolled sharing of physical access credentials", category: "Personnel", description: "Personnel allow others to use badges, keys, or equivalent credentials.", status: "Active" },
  { id: "VUL-0255", name: "Inadequate visitor supervision", category: "Personnel", description: "Responsible personnel do not maintain appropriate oversight of visitors.", status: "Active" },
  { id: "VUL-0256", name: "Excessive administrative errors", category: "Personnel", description: "Personnel repeatedly make incorrect security-relevant administrative changes.", status: "Active" },
  { id: "VUL-0257", name: "Failure to follow security procedures", category: "Personnel", description: "Personnel do not consistently perform activities according to approved procedures.", status: "Active" },
  { id: "VUL-0258", name: "Uncontrolled dependence on informal knowledge", category: "Personnel", description: "Required activities rely on undocumented individual knowledge.", status: "Active" },
  { id: "VUL-0259", name: "Excessive dependence on key personnel", category: "Personnel", description: "Critical activities rely on a small number of individuals without sufficient alternatives.", status: "Active" },
  { id: "VUL-0260", name: "Lack of backup personnel for critical roles", category: "Personnel", description: "No adequately prepared person is available to cover a critical role.", status: "Active" },
  { id: "VUL-0261", name: "Insufficient staffing levels", category: "Personnel", description: "Available personnel capacity is inadequate for required security and operational activities.", status: "Active" },
  { id: "VUL-0262", name: "Excessive workload affecting security responsibilities", category: "Personnel", description: "Work demands prevent personnel from performing security duties consistently.", status: "Active" },
  { id: "VUL-0263", name: "Susceptible to fatigue-related errors", category: "Personnel", description: "Working conditions increase the likelihood of security-relevant mistakes.", status: "Active" },
  { id: "VUL-0264", name: "Inadequate knowledge transfer", category: "Personnel", description: "Critical knowledge is not sufficiently transferred between personnel.", status: "Active" },
  { id: "VUL-0265", name: "Immature succession readiness", category: "Personnel", description: "Personnel are not adequately prepared to assume critical responsibilities.", status: "Active" },
  { id: "VUL-0266", name: "Failure to disclose conflicts of interest", category: "Personnel", description: "Personnel do not identify circumstances that may compromise impartial performance.", status: "Active" },
  { id: "VUL-0267", name: "Insufficient contractor security awareness", category: "Personnel", description: "Contractors lack adequate understanding of organizational security requirements.", status: "Active" },
  { id: "VUL-0268", name: "Uncontrolled retention of information by departing personnel", category: "Personnel", description: "Individuals retain protected organizational information after their engagement ends.", status: "Active" },
  { id: "VUL-0269", name: "Uncontrolled retention of access by departing personnel", category: "Personnel", description: "Departing individuals retain credentials or access mechanisms.", status: "Active" },
  { id: "VUL-0270", name: "Insecure handling of cryptographic material", category: "Personnel", description: "Personnel store, share, or use keys and certificates without adequate protection.", status: "Active" },
  { id: "VUL-0271", name: "Uncontrolled disabling of security tools", category: "Personnel", description: "Personnel turn off or interfere with security protections without authorization.", status: "Active" },
  { id: "VUL-0272", name: "Absence of information-security policies", category: "Organization", description: "The organization has not defined approved principles and expectations for information security.", status: "Active" },
  { id: "VUL-0273", name: "Outdated information-security policies", category: "Organization", description: "Policies no longer reflect current risks, obligations, technology, or operations.", status: "Active" },
  { id: "VUL-0274", name: "Failure to communicate information-security policies", category: "Organization", description: "Relevant personnel and parties are not made aware of applicable policies.", status: "Active" },
  { id: "VUL-0275", name: "Unclear security roles and responsibilities", category: "Organization", description: "Responsibility and authority for security activities are not clearly assigned.", status: "Active" },
  { id: "VUL-0276", name: "Absence of security control ownership", category: "Organization", description: "No accountable owner is designated for maintaining a required control.", status: "Active" },
  { id: "VUL-0277", name: "Inadequate management oversight of information security", category: "Organization", description: "Management does not sufficiently direct, monitor, or review security activities.", status: "Active" },
  { id: "VUL-0278", name: "Undefined information-security objectives", category: "Organization", description: "The organization has not established measurable intended security outcomes.", status: "Active" },
  { id: "VUL-0279", name: "Absence of security performance measurement", category: "Organization", description: "The organization does not evaluate whether security activities achieve intended results.", status: "Active" },
  { id: "VUL-0280", name: "Incomplete security metrics", category: "Organization", description: "Reported measures do not adequately represent security performance.", status: "Active" },
  { id: "VUL-0281", name: "Immature information-security governance", category: "Organization", description: "Security direction, accountability, oversight, and decision-making are inconsistently established.", status: "Active" },
  { id: "VUL-0282", name: "Inadequate periodic risk assessment", category: "Organization", description: "Information-security risks are not reassessed at planned intervals or after significant change.", status: "Active" },
  { id: "VUL-0283", name: "Undefined risk assessment criteria", category: "Organization", description: "Likelihood, impact, acceptance, and evaluation criteria are unclear or inconsistent.", status: "Active" },
  { id: "VUL-0284", name: "Incomplete risk assessments", category: "Organization", description: "Relevant assets, processes, threats, vulnerabilities, or impacts are omitted.", status: "Active" },
  { id: "VUL-0285", name: "Poor risk-treatment monitoring", category: "Organization", description: "Approved risk-treatment actions are not tracked through completion.", status: "Active" },
  { id: "VUL-0286", name: "Uncontrolled risk acceptance", category: "Organization", description: "Risks are accepted without appropriate review and authorization.", status: "Active" },
  { id: "VUL-0287", name: "Immature security exception management", category: "Organization", description: "Deviations from requirements are not consistently assessed, approved, monitored, and closed.", status: "Active" },
  { id: "VUL-0288", name: "Incomplete asset inventory", category: "Organization", description: "Organizational information and supporting assets are not fully identified.", status: "Active" },
  { id: "VUL-0289", name: "Unclear asset ownership", category: "Organization", description: "Assets lack accountable owners responsible for protection and lifecycle decisions.", status: "Active" },
  { id: "VUL-0290", name: "Inadequate asset classification", category: "Organization", description: "Assets are not consistently classified according to sensitivity and criticality.", status: "Active" },
  { id: "VUL-0291", name: "Undefined information-handling requirements", category: "Organization", description: "Required protection for different information classifications is not established.", status: "Active" },
  { id: "VUL-0292", name: "Undefined acceptable-use requirements", category: "Organization", description: "Permitted and prohibited uses of information and assets are unclear.", status: "Active" },
  { id: "VUL-0293", name: "Failure to verify asset return", category: "Organization", description: "Organizational assets are not confirmed as returned after role change or termination.", status: "Active" },
  { id: "VUL-0294", name: "Uncontrolled access provisioning", category: "Organization", description: "Access is granted without appropriate approval.", status: "Active" },
  { id: "VUL-0295", name: "Excessive access rights", category: "Organization", description: "Users or services receive more access than required for their responsibilities.", status: "Active" },
  { id: "VUL-0296", name: "Inadequate access reviews", category: "Organization", description: "Access rights are not periodically verified against current responsibilities.", status: "Active" },
  { id: "VUL-0297", name: "Failure to disable dormant accounts", category: "Organization", description: "Inactive accounts remain enabled and usable.", status: "Active" },
  { id: "VUL-0298", name: "Failure to remove orphaned accounts", category: "Organization", description: "Accounts remain active without a valid owner or business need.", status: "Active" },
  { id: "VUL-0299", name: "Inadequate access revocation", category: "Organization", description: "Access remains available after it is no longer required.", status: "Active" },
  { id: "VUL-0300", name: "Failure to review access after role changes", category: "Organization", description: "Access rights are not reassessed when responsibilities change.", status: "Active" },
  { id: "VUL-0301", name: "Inadequate segregation of duties", category: "Organization", description: "Conflicting responsibilities can be performed by the same person without sufficient oversight.", status: "Active" },
  { id: "VUL-0302", name: "Immature privileged-access governance", category: "Organization", description: "Elevated access is not consistently approved, limited, reviewed, and monitored.", status: "Active" },
  { id: "VUL-0303", name: "Uncontrolled use of shared accounts", category: "Organization", description: "Multiple persons use the same identity without adequate accountability.", status: "Active" },
  { id: "VUL-0304", name: "Unclear service-account ownership", category: "Organization", description: "Service accounts lack accountable owners and defined purposes.", status: "Active" },
  { id: "VUL-0305", name: "Undefined data classification requirements", category: "Organization", description: "The organization has not established how information sensitivity should be determined.", status: "Active" },
  { id: "VUL-0306", name: "Incomplete personal-data inventory", category: "Organization", description: "The organization cannot reliably identify all personal data it processes.", status: "Active" },
  { id: "VUL-0307", name: "Incomplete documentation of data flows", category: "Organization", description: "The movement of information between systems, locations, and parties is not fully understood.", status: "Active" },
  { id: "VUL-0308", name: "Absence of data-minimization requirements", category: "Organization", description: "Processes are not required to limit collection and use to necessary information.", status: "Active" },
  { id: "VUL-0309", name: "Undefined retention periods", category: "Organization", description: "The organization has not established how long information should be retained.", status: "Active" },
  { id: "VUL-0310", name: "Outdated retention schedules", category: "Organization", description: "Established retention rules no longer reflect current obligations or needs.", status: "Active" },
  { id: "VUL-0311", name: "Inadequate secure-deletion procedures", category: "Organization", description: "The organization lacks reliable methods for disposing of information.", status: "Active" },
  { id: "VUL-0312", name: "Missing deletion evidence", category: "Organization", description: "The organization cannot demonstrate that required information deletion occurred.", status: "Active" },
  { id: "VUL-0313", name: "Inadequate legal-hold procedures", category: "Organization", description: "Information subject to preservation requirements may be altered or deleted.", status: "Active" },
  { id: "VUL-0314", name: "Absence of documented lawful basis", category: "Organization", description: "The organization has not recorded the legal basis for processing personal data.", status: "Active" },
  { id: "VUL-0315", name: "Inadequate consent management", category: "Organization", description: "Consent is not consistently obtained, recorded, updated, and withdrawn.", status: "Active" },
  { id: "VUL-0316", name: "Incomplete privacy notices", category: "Organization", description: "Required information about personal-data processing is omitted.", status: "Active" },
  { id: "VUL-0317", name: "Outdated privacy notices", category: "Organization", description: "Published privacy information no longer reflects actual processing activities.", status: "Active" },
  { id: "VUL-0318", name: "Inadequate data-subject request procedures", category: "Organization", description: "Requests concerning personal-data rights cannot be consistently received and fulfilled.", status: "Active" },
  { id: "VUL-0319", name: "Failure to monitor data-subject request deadlines", category: "Organization", description: "Applicable response periods may expire without detection.", status: "Active" },
  { id: "VUL-0320", name: "Absence of privacy-impact assessments", category: "Organization", description: "High-risk or materially changed processing is not assessed for privacy impact.", status: "Active" },
  { id: "VUL-0321", name: "Undefined privacy-impact assessment triggers", category: "Organization", description: "The organization has not defined when a privacy assessment is required.", status: "Active" },
  { id: "VUL-0322", name: "Incomplete identification of cross-border transfers", category: "Organization", description: "International transfers of personal data are not systematically recorded.", status: "Active" },
  { id: "VUL-0323", name: "Unverified cross-border transfer safeguards", category: "Organization", description: "Required protection for international transfers is not adequately evaluated.", status: "Active" },
  { id: "VUL-0324", name: "Inadequate personal-data breach notification procedures", category: "Organization", description: "The organization cannot reliably assess and complete required breach notifications.", status: "Active" },
  { id: "VUL-0325", name: "Failure to monitor breach-notification deadlines", category: "Organization", description: "Applicable regulatory or contractual notification periods may be missed.", status: "Active" },
  { id: "VUL-0326", name: "Incomplete identification of applicable legal requirements", category: "Organization", description: "Relevant legal and regulatory obligations are not fully determined.", status: "Active" },
  { id: "VUL-0327", name: "Incomplete legal and regulatory register", category: "Organization", description: "The register of applicable obligations omits relevant requirements.", status: "Active" },
  { id: "VUL-0328", name: "Outdated legal and regulatory register", category: "Organization", description: "The register does not reflect current legal and regulatory requirements.", status: "Active" },
  { id: "VUL-0329", name: "Absence of regulatory change monitoring", category: "Organization", description: "New or amended requirements may not be identified promptly.", status: "Active" },
  { id: "VUL-0330", name: "Unclear ownership of compliance obligations", category: "Organization", description: "No responsible party is accountable for implementing specific obligations.", status: "Active" },
  { id: "VUL-0331", name: "Missing compliance evidence", category: "Organization", description: "The organization cannot demonstrate fulfilment of applicable requirements.", status: "Active" },
  { id: "VUL-0332", name: "Unclear regulatory reporting responsibilities", category: "Organization", description: "Responsibility for preparing, reviewing, and submitting required reports is not assigned.", status: "Active" },
  { id: "VUL-0333", name: "Failure to monitor regulatory reporting deadlines", category: "Organization", description: "Required regulatory submissions may not be completed on time.", status: "Active" },
  { id: "VUL-0334", name: "Incomplete identification of contractual security requirements", category: "Organization", description: "Security obligations contained in contracts are not systematically recorded.", status: "Active" },
  { id: "VUL-0335", name: "Unclear ownership of contractual obligations", category: "Organization", description: "No responsible party is assigned to fulfil particular contractual requirements.", status: "Active" },
  { id: "VUL-0336", name: "Absence of confidentiality obligations", category: "Organization", description: "Personnel or external parties are not bound by appropriate confidentiality requirements.", status: "Active" },
  { id: "VUL-0337", name: "Incomplete software-license inventory", category: "Organization", description: "The organization cannot reliably identify deployed software and applicable entitlements.", status: "Active" },
  { id: "VUL-0338", name: "Failure to assess open-source license obligations", category: "Organization", description: "Requirements associated with open-source components are not identified or fulfilled.", status: "Active" },
  { id: "VUL-0339", name: "Unclear intellectual-property ownership", category: "Organization", description: "Ownership and permitted use of created or acquired intellectual property are not defined.", status: "Active" },
  { id: "VUL-0340", name: "Undefined supplier security requirements", category: "Organization", description: "External providers are not given clear information-security requirements.", status: "Active" },
  { id: "VUL-0341", name: "Absence of supplier security assessments", category: "Organization", description: "Supplier security capability and risk are not evaluated.", status: "Active" },
  { id: "VUL-0342", name: "Insufficient supplier security monitoring", category: "Organization", description: "The organization does not verify continued fulfilment of supplier security requirements.", status: "Active" },
  { id: "VUL-0343", name: "Inadequate third-party access reviews", category: "Organization", description: "External access remains available without regular confirmation of need.", status: "Active" },
  { id: "VUL-0344", name: "Undefined third-party incident notification requirements", category: "Organization", description: "External parties are not required to report relevant incidents within an established period.", status: "Active" },
  { id: "VUL-0345", name: "Uncontrolled use of subprocessors", category: "Organization", description: "Downstream processing parties are engaged without adequate visibility, assessment, or approval.", status: "Active" },
  { id: "VUL-0346", name: "Inadequate supplier exit procedures", category: "Organization", description: "Access, information, assets, and dependencies are not securely resolved when a supplier relationship ends.", status: "Active" },
  { id: "VUL-0347", name: "Failure to assess supplier concentration risk", category: "Organization", description: "Operational dependence on one provider or shared dependency is not evaluated.", status: "Active" },
  { id: "VUL-0348", name: "Absence of security requirements in projects", category: "Organization", description: "Projects proceed without identifying and implementing relevant security requirements.", status: "Active" },
  { id: "VUL-0349", name: "Absence of security review in procurement", category: "Organization", description: "Technology or services are acquired without appropriate security evaluation.", status: "Active" },
  { id: "VUL-0350", name: "Missing security requirements in system design", category: "Organization", description: "Systems are designed without explicit security requirements.", status: "Active" },
  { id: "VUL-0351", name: "Immature change management", category: "Organization", description: "Changes are not consistently assessed, tested, approved, implemented, and reviewed.", status: "Active" },
  { id: "VUL-0352", name: "Failure to review emergency changes", category: "Organization", description: "Urgent changes remain in place without subsequent validation and approval.", status: "Active" },
  { id: "VUL-0353", name: "Absence of configuration baselines", category: "Organization", description: "Approved secure configuration requirements have not been defined.", status: "Active" },
  { id: "VUL-0354", name: "Failure to monitor configuration compliance", category: "Organization", description: "Deviations from approved configurations are not identified.", status: "Active" },
  { id: "VUL-0355", name: "Absence of vulnerability scanning", category: "Organization", description: "Relevant systems and applications are not systematically examined for known weaknesses.", status: "Active" },
  { id: "VUL-0356", name: "Undefined vulnerability remediation deadlines", category: "Organization", description: "Required timelines for correcting vulnerabilities have not been established.", status: "Active" },
  { id: "VUL-0357", name: "Unverified vulnerability remediation", category: "Organization", description: "Reported remediation is accepted without confirming that the weakness has been resolved.", status: "Active" },
  { id: "VUL-0358", name: "Incomplete security testing scope", category: "Organization", description: "Relevant systems, interfaces, environments, or attack paths are omitted from testing.", status: "Active" },
  { id: "VUL-0359", name: "Inadequate incident-response procedures", category: "Organization", description: "The organization lacks sufficient procedures to identify, contain, investigate, and recover from incidents.", status: "Active" },
  { id: "VUL-0360", name: "Unclear incident roles and escalation paths", category: "Organization", description: "Personnel do not know who is responsible for incident decisions and actions.", status: "Active" },
  { id: "VUL-0361", name: "Inconsistent security incident classification", category: "Organization", description: "Incidents are not consistently evaluated using defined severity and category criteria.", status: "Active" },
  { id: "VUL-0362", name: "Absence of incident-response exercises", category: "Organization", description: "Incident-response arrangements are not periodically tested.", status: "Active" },
  { id: "VUL-0363", name: "Failure to implement incident lessons learned", category: "Organization", description: "Identified improvements are not tracked and completed after incidents.", status: "Active" },
  { id: "VUL-0364", name: "Undefined logging requirements", category: "Organization", description: "The organization has not established which activities and events must be recorded.", status: "Active" },
  { id: "VUL-0365", name: "Undefined log-retention periods", category: "Organization", description: "The organization has not determined how long different logs must be retained.", status: "Active" },
  { id: "VUL-0366", name: "Unclear security monitoring responsibilities", category: "Organization", description: "Responsibility for reviewing and responding to alerts is not clearly assigned.", status: "Active" },
  { id: "VUL-0367", name: "Failure to review security alerts promptly", category: "Organization", description: "Generated alerts may remain unexamined beyond an acceptable period.", status: "Active" },
  { id: "VUL-0368", name: "Undefined backup requirements", category: "Organization", description: "The organization has not established what information and systems must be backed up.", status: "Active" },
  { id: "VUL-0369", name: "Insufficient backup frequency", category: "Organization", description: "Backup intervals do not meet business or recovery requirements.", status: "Active" },
  { id: "VUL-0370", name: "Incomplete backup coverage", category: "Organization", description: "Relevant information, configurations, or systems are omitted from backups.", status: "Active" },
  { id: "VUL-0371", name: "Excessive backup access rights", category: "Organization", description: "More persons or services can access backup information than necessary.", status: "Active" },
  { id: "VUL-0372", name: "Undefined recovery time objectives", category: "Organization", description: "Required service restoration times have not been established.", status: "Active" },
  { id: "VUL-0373", name: "Undefined recovery point objectives", category: "Organization", description: "Acceptable levels of information loss have not been established.", status: "Active" },
  { id: "VUL-0374", name: "Missing recovery procedures", category: "Organization", description: "Personnel lack approved instructions for restoring systems and information.", status: "Active" },
  { id: "VUL-0375", name: "Outdated recovery procedures", category: "Organization", description: "Recovery instructions no longer reflect current systems, dependencies, or responsibilities.", status: "Active" },
  { id: "VUL-0376", name: "Unverified disaster-recovery arrangements", category: "Organization", description: "The organization has not demonstrated its ability to recover from major disruption.", status: "Active" },
  { id: "VUL-0377", name: "Incomplete business continuity plans", category: "Organization", description: "Plans omit critical processes, dependencies, resources, or scenarios.", status: "Active" },
  { id: "VUL-0378", name: "Absence of business impact analysis", category: "Organization", description: "The organization has not determined the impact of process and service disruption.", status: "Active" },
  { id: "VUL-0379", name: "Incomplete identification of critical dependencies", category: "Organization", description: "Required systems, suppliers, personnel, facilities, or utilities are not fully understood.", status: "Active" },
  { id: "VUL-0380", name: "Inadequate crisis communication arrangements", category: "Organization", description: "The organization cannot reliably coordinate and communicate during significant disruption.", status: "Active" },
  { id: "VUL-0381", name: "Absence of internal security audits", category: "Organization", description: "The organization does not independently evaluate implementation of security requirements.", status: "Active" },
  { id: "VUL-0382", name: "Incomplete internal audit coverage", category: "Organization", description: "Relevant processes, systems, locations, or requirements are omitted from audits.", status: "Active" },
  { id: "VUL-0383", name: "Failure to resolve audit findings promptly", category: "Organization", description: "Identified weaknesses remain open beyond appropriate timeframes.", status: "Active" },
  { id: "VUL-0384", name: "Inadequate management review of information security", category: "Organization", description: "Management does not periodically evaluate the suitability and effectiveness of security arrangements.", status: "Active" },
  { id: "VUL-0385", name: "Immature document control", category: "Organization", description: "Security documents can become outdated, unapproved, unavailable, or unintentionally modified.", status: "Active" },
  { id: "VUL-0386", name: "Missing operational procedures", category: "Organization", description: "Required activities rely on informal or inconsistent working methods.", status: "Active" },
  { id: "VUL-0387", name: "Outdated operational procedures", category: "Organization", description: "Documented procedures no longer reflect current systems or practices.", status: "Active" },
  { id: "VUL-0388", name: "Incomplete records of security activities", category: "Organization", description: "The organization cannot demonstrate that required security activities occurred.", status: "Active" },
  { id: "VUL-0389", name: "Absence of AI governance requirements", category: "Organization", description: "The organization has not defined acceptable and secure use of artificial-intelligence systems.", status: "Active" },
  { id: "VUL-0390", name: "Incomplete AI system inventory", category: "Organization", description: "The organization cannot reliably identify AI systems used in its activities.", status: "Active" },
  { id: "VUL-0391", name: "Absence of AI risk assessments", category: "Organization", description: "Security, privacy, legal, and operational risks from AI use are not systematically evaluated.", status: "Active" },
  { id: "VUL-0392", name: "Absence of human oversight for automated decisions", category: "Organization", description: "High-impact automated decisions are made without suitable human review.", status: "Active" },
];
