// Canonical action keys used by requireAction across the app.
export const ACTIONS = {
  ORG_READ: "org.read",
  ORG_CREATE: "org.create",
  ORG_UPDATE: "org.update",
  ORG_ACTIVATE: "org.activate",
  ORG_SUSPEND: "org.suspend",
  ORG_DEACTIVATE: "org.deactivate",
  REGISTRATION_SUBMIT: "registration.submit",
  REGISTRATION_DECIDE: "registration.decide",
  USER_READ: "user.read",
  USER_CREATE: "user.create",
  USER_UPDATE: "user.update",
  USER_SUSPEND: "user.suspend",
  USER_DELETE: "user.delete",
  ROLE_ASSIGN: "role.assign",
  ROLE_READ: "role.read",
  ROLE_CREATE: "role.create",
  ROLE_UPDATE: "role.update",
  ROLE_GRANT: "role.grant",
  MENU_READ: "menu.read",
  MENU_MANAGE: "menu.manage",
  AUDIT_READ: "audit.read",
  PROFILE_READ: "profile.read",
  PROFILE_CREATE: "profile.create",
  PROFILE_UPDATE: "profile.update",
  PROFILE_DELETE: "profile.delete",
  ACCOUNT_READ: "account.read",
  ACCOUNT_CREATE: "account.create",
  ACCOUNT_UPDATE: "account.update",
  ACCOUNT_DELETE: "account.delete",
  FRAMEWORK_READ: "framework.read",
  FRAMEWORK_CREATE: "framework.create",
  FRAMEWORK_UPDATE: "framework.update",
  FRAMEWORK_DELETE: "framework.delete",
  REGISTRATION_READ: "registration.read",
  AGREEMENT_READ: "agreement.read",
  AGREEMENT_CREATE: "agreement.create",
  AGREEMENT_UPDATE: "agreement.update",
  AGREEMENT_DELETE: "agreement.delete",
  PARTNER_READ: "partner.read",
  PARTNER_CREATE: "partner.create",
  PARTNER_UPDATE: "partner.update",
  PARTNER_LIFECYCLE: "partner.lifecycle",
  PARTNER_AGREEMENT_MANAGE: "partnerAgreement.manage",
  PLAN_READ: "plan.read",
  PLAN_CREATE: "plan.create",
  PLAN_UPDATE: "plan.update",
  BILLING_READ: "billing.read",
  SITE_READ: "site.read",
  SITE_CREATE: "site.create",
  SITE_UPDATE: "site.update",
  SITE_DELETE: "site.delete",
  SITE_PROVISION: "site.provision",
  SITE_REQUEST_READ: "siteRequest.read",
  SITE_REQUEST_SUBMIT: "siteRequest.submit",
  SITE_REQUEST_DECIDE: "siteRequest.decide",
  REQUIREMENT_READ: "requirement.read",
  REQUIREMENT_CREATE: "requirement.create",
  REQUIREMENT_UPDATE: "requirement.update",
  REQUIREMENT_DELETE: "requirement.delete",
  ELEMENT_READ: "element.read",
  ELEMENT_CREATE: "element.create",
  ELEMENT_UPDATE: "element.update",
  ELEMENT_DELETE: "element.delete",
  ELEMENT_MAPPING_MANAGE: "elementMapping.manage",
  CRITERION_READ: "criterion.read",
  CRITERION_MANAGE: "criterion.manage",
  XREF_READ: "frameworkXref.read",
  ASSESSMENT_READ: "assessment.read",
  ASSESSMENT_MANAGE: "assessment.manage",
  FRAMEWORK_GROUP_READ: "frameworkGroup.read",
  ORG_BRANDING_MANAGE: "org.branding.manage",
  ORG_DEFAULTS_MANAGE: "org.defaults.manage",
  SIGNATORY_READ: "signatory.read",
  SIGNATORY_CREATE: "signatory.create",
  SIGNATORY_UPDATE: "signatory.update",
  KB_READ: "kb.read",
  KB_CREATE: "kb.create",
  KB_UPDATE: "kb.update",
  KB_PUBLISH: "kb.publish",
  KB_ARCHIVE: "kb.archive",
  TICKET_READ: "ticket.read",
  TICKET_CREATE: "ticket.create",
  TICKET_REPLY: "ticket.reply",
  TICKET_MANAGE: "ticket.manage",
  IMPLEMENTATION_READ: "implementation.read",
  IMPLEMENTATION_CREATE: "implementation.create",
  IMPLEMENTATION_UPDATE: "implementation.update",
  IMPLEMENTATION_DELETE: "implementation.delete",
  TENANT_READ: "tenant.read",
  TENANT_PROVISION: "tenant.provision",
  FRAMEWORK_ASSIGNMENT_READ: "frameworkAssignment.read",
  FRAMEWORK_ASSIGNMENT_CREATE: "frameworkAssignment.create",
  FRAMEWORK_ASSIGNMENT_UPDATE: "frameworkAssignment.update",
  FRAMEWORK_ASSIGNMENT_DELETE: "frameworkAssignment.delete",
  MODULE_READ: "module.read",
} as const;

export type ActionKey = (typeof ACTIONS)[keyof typeof ACTIONS];

export interface SeedAction {
  key: string;
  name: string;
}
export interface SeedMenu {
  name: string;
  heading?: string;
  route?: string;
  routeSeo?: string;
  icon?: string;
  actions?: SeedAction[];
  children?: SeedMenu[];
}

/** The default navigable menu tree + the actions available under each menu. */
export const MENU_SEED: SeedMenu[] = [
  { name: "Dashboard", route: "/dashboard", routeSeo: "dashboard", icon: "grid" },
  {
    name: "User Management",
    heading: "User Management",
    icon: "users",
    children: [
      {
        name: "Organizations",
        route: "/organizations",
        routeSeo: "organizations",
        icon: "building",
        actions: [
          { key: ACTIONS.ORG_READ, name: "View organizations" },
          { key: ACTIONS.ORG_CREATE, name: "Create organization" },
          { key: ACTIONS.ORG_UPDATE, name: "Edit organization" },
          { key: ACTIONS.ORG_ACTIVATE, name: "Activate organization" },
          { key: ACTIONS.ORG_SUSPEND, name: "Suspend organization" },
          { key: ACTIONS.ORG_DEACTIVATE, name: "Deactivate organization" },
          { key: ACTIONS.ORG_BRANDING_MANAGE, name: "Manage organization branding" },
          { key: ACTIONS.ORG_DEFAULTS_MANAGE, name: "Manage organization defaults" },
          { key: ACTIONS.SIGNATORY_READ, name: "View signatories" },
          { key: ACTIONS.SIGNATORY_CREATE, name: "Add signatory" },
          { key: ACTIONS.SIGNATORY_UPDATE, name: "Edit/toggle signatory" },
          { key: ACTIONS.REGISTRATION_SUBMIT, name: "Submit tenant registration" },
          { key: ACTIONS.REGISTRATION_DECIDE, name: "Approve/reject registration" },
          { key: ACTIONS.REGISTRATION_READ, name: "View registration requests" },
        ],
      },
      {
        name: "Users",
        route: "/users",
        routeSeo: "users",
        icon: "user",
        actions: [
          { key: ACTIONS.USER_READ, name: "View users" },
          { key: ACTIONS.USER_CREATE, name: "Create user" },
          { key: ACTIONS.USER_UPDATE, name: "Edit user" },
          { key: ACTIONS.USER_SUSPEND, name: "Suspend/deactivate user" },
          { key: ACTIONS.USER_DELETE, name: "Remove user" },
          { key: ACTIONS.ROLE_ASSIGN, name: "Assign/remove role" },
        ],
      },
      {
        name: "Roles & Access",
        route: "/roles",
        routeSeo: "roles",
        icon: "shield",
        actions: [
          { key: ACTIONS.ROLE_READ, name: "View roles" },
          { key: ACTIONS.ROLE_CREATE, name: "Create role" },
          { key: ACTIONS.ROLE_UPDATE, name: "Edit role" },
          { key: ACTIONS.ROLE_GRANT, name: "Edit role grants" },
        ],
      },
      {
        name: "Menus",
        route: "/menus",
        routeSeo: "menus",
        icon: "list",
        actions: [
          { key: ACTIONS.MENU_READ, name: "View menus" },
          { key: ACTIONS.MENU_MANAGE, name: "Manage menus/actions" },
        ],
      },
      {
        name: "Audit Log",
        route: "/audit",
        routeSeo: "audit",
        icon: "history",
        actions: [{ key: ACTIONS.AUDIT_READ, name: "View audit log" }],
      },
      {
        name: "Profiles",
        route: "/profiles",
        routeSeo: "profiles",
        icon: "id-card",
        actions: [
          { key: ACTIONS.PROFILE_READ, name: "View profiles" },
          { key: ACTIONS.PROFILE_CREATE, name: "Create profile" },
          { key: ACTIONS.PROFILE_UPDATE, name: "Edit profile" },
          { key: ACTIONS.PROFILE_DELETE, name: "Delete profile" },
        ],
      },
      {
        name: "Accounts",
        route: "/accounts",
        routeSeo: "accounts",
        icon: "link",
        actions: [
          { key: ACTIONS.ACCOUNT_READ, name: "View accounts" },
          { key: ACTIONS.ACCOUNT_CREATE, name: "Create account" },
          { key: ACTIONS.ACCOUNT_UPDATE, name: "Edit account" },
          { key: ACTIONS.ACCOUNT_DELETE, name: "Delete account" },
        ],
      },
    ],
  },
  {
    name: "Framework Configuration",
    heading: "Framework Configuration",
    icon: "layers",
    children: [
      {
        name: "Framework Library",
        route: "/frameworks",
        routeSeo: "frameworks",
        icon: "layers",
        actions: [
          { key: ACTIONS.FRAMEWORK_READ, name: "View frameworks" },
          { key: ACTIONS.FRAMEWORK_CREATE, name: "Create framework" },
          { key: ACTIONS.FRAMEWORK_UPDATE, name: "Edit framework" },
          { key: ACTIONS.FRAMEWORK_DELETE, name: "Delete framework" },
        ],
      },
    ],
  },
  {
    name: "Commercial",
    heading: "Commercial",
    icon: "handshake",
    children: [
      {
        name: "Partner Management",
        route: "/partners",
        routeSeo: "partners",
        icon: "handshake",
        actions: [
          { key: ACTIONS.PARTNER_READ, name: "View partners" },
          { key: ACTIONS.PARTNER_CREATE, name: "Create partner" },
          { key: ACTIONS.PARTNER_UPDATE, name: "Edit partner" },
          { key: ACTIONS.PARTNER_LIFECYCLE, name: "Partner lifecycle actions" },
          { key: ACTIONS.PARTNER_AGREEMENT_MANAGE, name: "Manage partner agreements" },
        ],
      },
      {
        name: "Partnership Agreements",
        route: "/partnership-agreements",
        routeSeo: "partnership-agreements",
        icon: "file-text",
        actions: [
          { key: ACTIONS.AGREEMENT_READ, name: "View partnership agreements" },
          { key: ACTIONS.AGREEMENT_CREATE, name: "Create partnership agreement" },
          { key: ACTIONS.AGREEMENT_UPDATE, name: "Edit partnership agreement" },
          { key: ACTIONS.AGREEMENT_DELETE, name: "Delete partnership agreement" },
        ],
      },
      {
        name: "Billing Management",
        route: "/billing/subscriptions",
        routeSeo: "billing",
        icon: "credit-card",
        actions: [
          { key: ACTIONS.BILLING_READ, name: "View billing" },
          { key: ACTIONS.PLAN_READ, name: "View plans" },
          { key: ACTIONS.PLAN_CREATE, name: "Create plan" },
          { key: ACTIONS.PLAN_UPDATE, name: "Edit plan" },
        ],
      },
    ],
  },
  {
    name: "Tenant Operations",
    heading: "Tenant Operations",
    icon: "building",
    children: [
      {
        name: "Tenants",
        route: "/tenants",
        routeSeo: "tenants",
        icon: "building",
        actions: [
          { key: ACTIONS.TENANT_READ, name: "View tenants" },
          { key: ACTIONS.TENANT_PROVISION, name: "Provision a tenant" },
          { key: ACTIONS.ORG_ACTIVATE, name: "Activate tenant" },
          { key: ACTIONS.ORG_SUSPEND, name: "Suspend tenant" },
          { key: ACTIONS.ORG_DEACTIVATE, name: "Deactivate tenant" },
          { key: ACTIONS.SITE_READ, name: "View tenant sites" },
          { key: ACTIONS.SITE_CREATE, name: "Add tenant site" },
          { key: ACTIONS.SITE_UPDATE, name: "Edit tenant site" },
          { key: ACTIONS.SITE_DELETE, name: "Remove tenant site" },
          { key: ACTIONS.FRAMEWORK_ASSIGNMENT_READ, name: "View framework assignments" },
          { key: ACTIONS.FRAMEWORK_ASSIGNMENT_CREATE, name: "Assign framework" },
          { key: ACTIONS.FRAMEWORK_ASSIGNMENT_UPDATE, name: "Edit framework assignment" },
          { key: ACTIONS.FRAMEWORK_ASSIGNMENT_DELETE, name: "Remove framework assignment" },
          { key: ACTIONS.AUDIT_READ, name: "View tenant audit log" },
        ],
      },
      {
        name: "Tenant Provisioning",
        route: "/tenant-provisioning",
        routeSeo: "tenant-provisioning",
        icon: "building",
        actions: [
          { key: ACTIONS.REGISTRATION_READ, name: "View tenant provisioning queue" },
          { key: ACTIONS.REGISTRATION_DECIDE, name: "Provision tenant from request" },
        ],
      },
      {
        name: "Site Requests",
        route: "/site-requests",
        routeSeo: "site-requests",
        icon: "map-pin",
        actions: [
          { key: ACTIONS.SITE_REQUEST_READ, name: "View site requests" },
          { key: ACTIONS.SITE_REQUEST_SUBMIT, name: "Submit a site request" },
          { key: ACTIONS.SITE_REQUEST_DECIDE, name: "Approve/reject site requests" },
        ],
      },
      {
        name: "Site Provisioning",
        route: "/site-provisioning",
        routeSeo: "site-provisioning",
        icon: "map-pin",
        actions: [
          { key: ACTIONS.SITE_READ, name: "View sites" },
          { key: ACTIONS.SITE_CREATE, name: "Create site" },
          { key: ACTIONS.SITE_UPDATE, name: "Edit site" },
          { key: ACTIONS.SITE_DELETE, name: "Delete site" },
          { key: ACTIONS.SITE_PROVISION, name: "Provision a site from a request" },
        ],
      },
    ],
  },
  {
    name: "Framework Implementation",
    heading: "Framework Implementation",
    icon: "layers",
    children: [
      {
        name: "Requirement Library",
        route: "/requirement-library",
        routeSeo: "requirement-library",
        icon: "file-text",
        actions: [
          { key: ACTIONS.REQUIREMENT_READ, name: "View requirements" },
          { key: ACTIONS.REQUIREMENT_CREATE, name: "Create requirement" },
          { key: ACTIONS.REQUIREMENT_UPDATE, name: "Edit requirement" },
          { key: ACTIONS.REQUIREMENT_DELETE, name: "Delete requirement" },
          { key: ACTIONS.CRITERION_READ, name: "View assessment criteria" },
          { key: ACTIONS.CRITERION_MANAGE, name: "Manage assessment criteria" },
        ],
      },
      {
        name: "Element Library",
        route: "/element-library",
        routeSeo: "element-library",
        icon: "share-2",
        actions: [
          { key: ACTIONS.ELEMENT_READ, name: "View framework elements" },
          { key: ACTIONS.ELEMENT_CREATE, name: "Create framework element" },
          { key: ACTIONS.ELEMENT_UPDATE, name: "Edit framework element" },
          { key: ACTIONS.ELEMENT_DELETE, name: "Delete framework element" },
          { key: ACTIONS.ELEMENT_MAPPING_MANAGE, name: "Manage element-requirement mappings" },
        ],
      },
      {
        name: "Assessment Library",
        route: "/assessments",
        routeSeo: "assessments",
        icon: "clipboard",
        actions: [
          { key: ACTIONS.ASSESSMENT_READ, name: "View assessments" },
          { key: ACTIONS.ASSESSMENT_MANAGE, name: "Manage assessment questions/responses" },
        ],
      },
      {
        name: "Cross-Reference",
        route: "/cross-references/elements",
        routeSeo: "cross-references-elements",
        icon: "git-compare",
        actions: [
          { key: ACTIONS.XREF_READ, name: "View cross-reference mappings" },
          { key: ACTIONS.FRAMEWORK_GROUP_READ, name: "View framework groups" },
        ],
      },
    ],
  },
  {
    name: "Support",
    heading: "Support",
    icon: "help-circle",
    children: [
      {
        name: "Knowledge Base",
        route: "/knowledge-base",
        routeSeo: "knowledge-base",
        icon: "book",
        actions: [
          { key: ACTIONS.KB_READ, name: "View knowledge base" },
          { key: ACTIONS.KB_CREATE, name: "Create article" },
          { key: ACTIONS.KB_UPDATE, name: "Edit article" },
          { key: ACTIONS.KB_PUBLISH, name: "Publish article" },
          { key: ACTIONS.KB_ARCHIVE, name: "Archive article" },
        ],
      },
      {
        name: "Ticket Management",
        route: "/tickets",
        routeSeo: "tickets",
        icon: "ticket",
        actions: [
          { key: ACTIONS.TICKET_READ, name: "View tickets" },
          { key: ACTIONS.TICKET_CREATE, name: "Create ticket" },
          { key: ACTIONS.TICKET_REPLY, name: "Reply to ticket" },
          { key: ACTIONS.TICKET_MANAGE, name: "Assign / change ticket status" },
        ],
      },
    ],
  },
  {
    name: "Implementation",
    heading: "Implementation",
    icon: "list-checks",
    children: [
      {
        name: "Documents",
        route: "/implementation/documents",
        routeSeo: "implementation-documents",
        icon: "file-text",
        actions: [
          { key: ACTIONS.IMPLEMENTATION_READ, name: "View implementation registers" },
          { key: ACTIONS.IMPLEMENTATION_CREATE, name: "Create implementation record" },
          { key: ACTIONS.IMPLEMENTATION_UPDATE, name: "Edit implementation record" },
          { key: ACTIONS.IMPLEMENTATION_DELETE, name: "Delete implementation record" },
        ],
      },
      { name: "Compliance", route: "/implementation/compliance", routeSeo: "implementation-compliance", icon: "shield" },
      { name: "Risks", route: "/implementation/risks", routeSeo: "implementation-risks", icon: "alert-triangle" },
      { name: "Competence", route: "/implementation/competence", routeSeo: "implementation-competence", icon: "users" },
      { name: "Objectives & KPI", route: "/implementation/objectives", routeSeo: "implementation-objectives", icon: "target" },
      { name: "Internal Audits", route: "/implementation/audits", routeSeo: "implementation-audits", icon: "clipboard" },
      { name: "Management Reviews", route: "/implementation/reviews", routeSeo: "implementation-reviews", icon: "eye" },
      { name: "Incidents & Nonconformities", route: "/implementation/incidents", routeSeo: "implementation-incidents", icon: "alert-octagon" },
    ],
  },
];
