// Canonical action keys used by requireAction across the app.
export const ACTIONS = {
  ORG_READ: "org.read",
  ORG_CREATE: "org.create",
  ORG_UPDATE: "org.update",
  ORG_ACTIVATE: "org.activate",
  ORG_SUSPEND: "org.suspend",
  REGISTRATION_SUBMIT: "registration.submit",
  REGISTRATION_DECIDE: "registration.decide",
  USER_READ: "user.read",
  USER_CREATE: "user.create",
  USER_UPDATE: "user.update",
  USER_SUSPEND: "user.suspend",
  USER_DELETE: "user.delete",
  ROLE_ASSIGN: "role.assign",
  ROLE_READ: "role.read",
  ROLE_CREATE: "role.create",
  ROLE_UPDATE: "role.update",
  ROLE_GRANT: "role.grant",
  MENU_READ: "menu.read",
  MENU_MANAGE: "menu.manage",
  AUDIT_READ: "audit.read",
  PROFILE_READ: "profile.read",
  PROFILE_CREATE: "profile.create",
  PROFILE_UPDATE: "profile.update",
  PROFILE_DELETE: "profile.delete",
  ACCOUNT_READ: "account.read",
  ACCOUNT_CREATE: "account.create",
  ACCOUNT_UPDATE: "account.update",
  ACCOUNT_DELETE: "account.delete",
  SIGNATORY_READ: "signatory.read",
  SIGNATORY_CREATE: "signatory.create",
  SIGNATORY_UPDATE: "signatory.update",
  SIGNATORY_DELETE: "signatory.delete",
  PARTNER_READ: "partner.read",
  PARTNER_CREATE: "partner.create",
  PARTNER_UPDATE: "partner.update",
  PARTNER_DELETE: "partner.delete",
  AGREEMENT_READ: "agreement.read",
  AGREEMENT_CREATE: "agreement.create",
  AGREEMENT_UPDATE: "agreement.update",
  AGREEMENT_DELETE: "agreement.delete",
  TENANT_READ: "tenant.read",
  TENANT_CREATE: "tenant.create",
  TENANT_UPDATE: "tenant.update",
  SITE_READ: "site.read",
  SITE_CREATE: "site.create",
  SITE_UPDATE: "site.update",
  SITE_DELETE: "site.delete",
  SITE_REQUEST_READ: "siteRequest.read",
  SITE_REQUEST_CREATE: "siteRequest.create",
  SITE_REQUEST_DECIDE: "siteRequest.decide",
  FRAMEWORK_ASSIGNMENT_READ: "frameworkAssignment.read",
  FRAMEWORK_ASSIGNMENT_CREATE: "frameworkAssignment.create",
  FRAMEWORK_ASSIGNMENT_UPDATE: "frameworkAssignment.update",
  FRAMEWORK_ASSIGNMENT_DELETE: "frameworkAssignment.delete",
  BILLING_READ: "billing.read",
  BILLING_MANAGE: "billing.manage",
  TICKET_READ: "ticket.read",
  TICKET_CREATE: "ticket.create",
  TICKET_REPLY: "ticket.reply",
  TICKET_MANAGE: "ticket.manage",
  ELEMENT_READ: "element.read",
  ELEMENT_MANAGE: "element.manage",
  REQUIREMENT_READ: "requirement.read",
  REQUIREMENT_MANAGE: "requirement.manage",
  ASSESSMENT_READ: "assessment.read",
  ASSESSMENT_MANAGE: "assessment.manage",
  FRAMEWORK_TYPE_READ: "frameworkType.read",
  FRAMEWORK_TYPE_CREATE: "frameworkType.create",
  FRAMEWORK_TYPE_UPDATE: "frameworkType.update",
  FRAMEWORK_TYPE_DELETE: "frameworkType.delete",
  FRAMEWORK_FAMILY_READ: "frameworkFamily.read",
  FRAMEWORK_FAMILY_CREATE: "frameworkFamily.create",
  FRAMEWORK_FAMILY_UPDATE: "frameworkFamily.update",
  FRAMEWORK_FAMILY_DELETE: "frameworkFamily.delete",
  FRAMEWORK_READ: "framework.read",
  FRAMEWORK_CREATE: "framework.create",
  FRAMEWORK_UPDATE: "framework.update",
  FRAMEWORK_DELETE: "framework.delete",
  FRAMEWORK_CATALOG_READ: "frameworkCatalog.read",
  FRAMEWORK_CATALOG_SUBSCRIBE: "frameworkCatalog.subscribe",
  MY_FRAMEWORK_READ: "myFramework.read",
  MY_FRAMEWORK_DELETE: "myFramework.delete",
  ASSESSMENT_RUN_READ: "assessmentRun.read",
  ASSESSMENT_RUN_MANAGE: "assessmentRun.manage",
  MS_READ: "ms.read",
  MS_MANAGE: "ms.manage",
  LIMS_READ: "lims.read",
  LIMS_MANAGE: "lims.manage",
  KB_READ: "kb.read",
  KB_MANAGE: "kb.manage",
} as const;

export type ActionKey = (typeof ACTIONS)[keyof typeof ACTIONS];

export interface SeedAction {
  key: string;
  name: string;
}
export interface SeedMenu {
  name: string;
  heading?: string;
  route?: string;
  routeSeo?: string;
  icon?: string;
  actions?: SeedAction[];
  children?: SeedMenu[];
}

/** The default navigable menu tree + the actions available under each menu. */
export const MENU_SEED: SeedMenu[] = [
  { name: "Dashboard", route: "/dashboard", routeSeo: "dashboard", icon: "grid" },
  {
    name: "User Management",
    heading: "User Management",
    icon: "users",
    children: [
      {
        name: "Organizations",
        route: "/organizations",
        routeSeo: "organizations",
        icon: "building",
        actions: [
          { key: ACTIONS.ORG_READ, name: "View organizations" },
          { key: ACTIONS.ORG_CREATE, name: "Create organization" },
          { key: ACTIONS.ORG_UPDATE, name: "Edit organization" },
          { key: ACTIONS.ORG_ACTIVATE, name: "Activate organization" },
          { key: ACTIONS.ORG_SUSPEND, name: "Suspend organization" },
          { key: ACTIONS.REGISTRATION_SUBMIT, name: "Submit tenant registration" },
          { key: ACTIONS.REGISTRATION_DECIDE, name: "Approve/reject registration" },
        ],
      },
      {
        name: "Users",
        route: "/users",
        routeSeo: "users",
        icon: "user",
        actions: [
          { key: ACTIONS.USER_READ, name: "View users" },
          { key: ACTIONS.USER_CREATE, name: "Create user" },
          { key: ACTIONS.USER_UPDATE, name: "Edit user" },
          { key: ACTIONS.USER_SUSPEND, name: "Suspend/deactivate user" },
          { key: ACTIONS.USER_DELETE, name: "Remove user" },
          { key: ACTIONS.ROLE_ASSIGN, name: "Assign/remove role" },
        ],
      },
      {
        name: "Roles & Access",
        route: "/roles",
        routeSeo: "roles",
        icon: "shield",
        actions: [
          { key: ACTIONS.ROLE_READ, name: "View roles" },
          { key: ACTIONS.ROLE_CREATE, name: "Create role" },
          { key: ACTIONS.ROLE_UPDATE, name: "Edit role" },
          { key: ACTIONS.ROLE_GRANT, name: "Edit role grants" },
        ],
      },
      {
        name: "Menus",
        route: "/menus",
        routeSeo: "menus",
        icon: "list",
        actions: [
          { key: ACTIONS.MENU_READ, name: "View menus" },
          { key: ACTIONS.MENU_MANAGE, name: "Manage menus/actions" },
        ],
      },
      {
        name: "Audit Log",
        route: "/audit",
        routeSeo: "audit",
        icon: "history",
        actions: [{ key: ACTIONS.AUDIT_READ, name: "View audit log" }],
      },
      {
        name: "Profiles",
        route: "/profiles",
        routeSeo: "profiles",
        icon: "id-card",
        actions: [
          { key: ACTIONS.PROFILE_READ, name: "View profiles" },
          { key: ACTIONS.PROFILE_CREATE, name: "Create profile" },
          { key: ACTIONS.PROFILE_UPDATE, name: "Edit profile" },
          { key: ACTIONS.PROFILE_DELETE, name: "Delete profile" },
        ],
      },
      {
        name: "Accounts",
        route: "/accounts",
        routeSeo: "accounts",
        icon: "link",
        actions: [
          { key: ACTIONS.ACCOUNT_READ, name: "View accounts" },
          { key: ACTIONS.ACCOUNT_CREATE, name: "Create account" },
          { key: ACTIONS.ACCOUNT_UPDATE, name: "Edit account" },
          { key: ACTIONS.ACCOUNT_DELETE, name: "Delete account" },
        ],
      },
      {
        name: "Organization Settings",
        route: "/settings",
        routeSeo: "settings",
        icon: "settings",
        actions: [
          { key: ACTIONS.SIGNATORY_READ, name: "View signatories" },
          { key: ACTIONS.SIGNATORY_CREATE, name: "Add signatory" },
          { key: ACTIONS.SIGNATORY_UPDATE, name: "Edit signatory" },
          { key: ACTIONS.SIGNATORY_DELETE, name: "Delete signatory" },
        ],
      },
    ],
  },
  {
    name: "Commercial",
    heading: "Commercial",
    icon: "handshake",
    children: [
      {
        name: "Partners",
        route: "/partners",
        routeSeo: "partners",
        icon: "building",
        actions: [
          { key: ACTIONS.PARTNER_READ, name: "View partners" },
          { key: ACTIONS.PARTNER_CREATE, name: "Create partner" },
          { key: ACTIONS.PARTNER_UPDATE, name: "Edit partner / lifecycle" },
          { key: ACTIONS.PARTNER_DELETE, name: "Delete partner" },
        ],
      },
      {
        name: "Partnership Agreements",
        route: "/partnership-agreements",
        routeSeo: "partnership-agreements",
        icon: "file-text",
        actions: [
          { key: ACTIONS.AGREEMENT_READ, name: "View agreement templates" },
          { key: ACTIONS.AGREEMENT_CREATE, name: "Create agreement template" },
          { key: ACTIONS.AGREEMENT_UPDATE, name: "Edit agreement template" },
          { key: ACTIONS.AGREEMENT_DELETE, name: "Delete agreement template" },
        ],
      },
      {
        name: "Billing",
        route: "/billing/subscriptions",
        routeSeo: "billing",
        icon: "credit-card",
        actions: [
          { key: ACTIONS.BILLING_READ, name: "View billing" },
          { key: ACTIONS.BILLING_MANAGE, name: "Manage plans / payments / payouts" },
        ],
      },
    ],
  },
  {
    name: "Tenant Management",
    heading: "Tenant Management",
    icon: "boxes",
    children: [
      {
        name: "Tenants",
        route: "/tenants",
        routeSeo: "tenants",
        icon: "building",
        actions: [
          { key: ACTIONS.TENANT_READ, name: "View tenants" },
          { key: ACTIONS.TENANT_CREATE, name: "Provision tenant" },
          { key: ACTIONS.TENANT_UPDATE, name: "Tenant lifecycle" },
          { key: ACTIONS.FRAMEWORK_ASSIGNMENT_READ, name: "View framework assignments" },
          { key: ACTIONS.FRAMEWORK_ASSIGNMENT_CREATE, name: "Create framework assignment" },
          { key: ACTIONS.FRAMEWORK_ASSIGNMENT_UPDATE, name: "Edit framework assignment" },
          { key: ACTIONS.FRAMEWORK_ASSIGNMENT_DELETE, name: "Delete framework assignment" },
        ],
      },
      {
        name: "Sites",
        route: "/sites",
        routeSeo: "sites",
        icon: "map-pin",
        actions: [
          { key: ACTIONS.SITE_READ, name: "View sites" },
          { key: ACTIONS.SITE_CREATE, name: "Create site" },
          { key: ACTIONS.SITE_UPDATE, name: "Edit site" },
          { key: ACTIONS.SITE_DELETE, name: "Delete site" },
        ],
      },
      {
        name: "Site Requests",
        route: "/site-requests",
        routeSeo: "site-requests",
        icon: "file-text",
        actions: [
          { key: ACTIONS.SITE_REQUEST_READ, name: "View site requests" },
          { key: ACTIONS.SITE_REQUEST_CREATE, name: "Submit site request" },
          { key: ACTIONS.SITE_REQUEST_DECIDE, name: "Review/approve/provision site request" },
        ],
      },
    ],
  },
  {
    name: "Support",
    heading: "Support",
    icon: "life-buoy",
    children: [
      {
        name: "Tickets",
        route: "/tickets",
        routeSeo: "tickets",
        icon: "ticket",
        actions: [
          { key: ACTIONS.TICKET_READ, name: "View tickets" },
          { key: ACTIONS.TICKET_CREATE, name: "Create ticket" },
          { key: ACTIONS.TICKET_REPLY, name: "Reply to ticket" },
          { key: ACTIONS.TICKET_MANAGE, name: "Assign / change status" },
        ],
      },
      {
        name: "Knowledge Base",
        route: "/knowledge-base",
        routeSeo: "knowledge-base",
        icon: "book-open",
        actions: [
          { key: ACTIONS.KB_READ, name: "View knowledge base" },
          { key: ACTIONS.KB_MANAGE, name: "Author / publish articles" },
        ],
      },
    ],
  },
  {
    name: "Compliance",
    heading: "Compliance",
    icon: "clipboard-check",
    children: [
      {
        name: "Gap Assessment",
        route: "/gap-assessment",
        routeSeo: "gap-assessment",
        icon: "clipboard-check",
        actions: [
          { key: ACTIONS.ASSESSMENT_RUN_READ, name: "View assessments + gap analysis" },
          { key: ACTIONS.ASSESSMENT_RUN_MANAGE, name: "Run assessment / answer / finalize" },
        ],
      },
      {
        name: "Management System",
        route: "/implementation",
        routeSeo: "implementation",
        icon: "clipboard-list",
        actions: [
          { key: ACTIONS.MS_READ, name: "View clause registers" },
          { key: ACTIONS.MS_MANAGE, name: "Manage clause-register entries" },
        ],
      },
    ],
  },
  {
    name: "Laboratory",
    heading: "Laboratory",
    icon: "flask-conical",
    children: [
      {
        name: "LIMS",
        route: "/lab",
        routeSeo: "lab",
        icon: "flask-conical",
        actions: [
          { key: ACTIONS.LIMS_READ, name: "View testing services + workflow" },
          { key: ACTIONS.LIMS_MANAGE, name: "Manage testing services + stage config" },
        ],
      },
    ],
  },
  {
    name: "Framework Configuration",
    heading: "Framework Configuration",
    icon: "layers",
    children: [
      {
        name: "Framework Types",
        route: "/framework-types",
        routeSeo: "framework-types",
        icon: "layers",
        actions: [
          { key: ACTIONS.FRAMEWORK_TYPE_READ, name: "View framework types" },
          { key: ACTIONS.FRAMEWORK_TYPE_CREATE, name: "Create framework type" },
          { key: ACTIONS.FRAMEWORK_TYPE_UPDATE, name: "Edit framework type" },
          { key: ACTIONS.FRAMEWORK_TYPE_DELETE, name: "Delete framework type" },
        ],
      },
      {
        name: "Framework Families",
        route: "/framework-families",
        routeSeo: "framework-families",
        icon: "layers",
        actions: [
          { key: ACTIONS.FRAMEWORK_FAMILY_READ, name: "View framework families" },
          { key: ACTIONS.FRAMEWORK_FAMILY_CREATE, name: "Create framework family" },
          { key: ACTIONS.FRAMEWORK_FAMILY_UPDATE, name: "Edit framework family" },
          { key: ACTIONS.FRAMEWORK_FAMILY_DELETE, name: "Delete framework family" },
        ],
      },
      {
        name: "Frameworks",
        route: "/frameworks",
        routeSeo: "frameworks",
        icon: "layers",
        actions: [
          { key: ACTIONS.FRAMEWORK_READ, name: "View frameworks" },
          { key: ACTIONS.FRAMEWORK_CREATE, name: "Create framework" },
          { key: ACTIONS.FRAMEWORK_UPDATE, name: "Edit framework" },
          { key: ACTIONS.FRAMEWORK_DELETE, name: "Delete framework" },
        ],
      },
      {
        name: "Requirement Library",
        route: "/requirement-library",
        routeSeo: "requirement-library",
        icon: "file-text",
        actions: [
          { key: ACTIONS.REQUIREMENT_READ, name: "View requirements" },
          { key: ACTIONS.REQUIREMENT_MANAGE, name: "Manage requirements + criteria" },
        ],
      },
      {
        name: "Element Library",
        route: "/element-library",
        routeSeo: "element-library",
        icon: "share-2",
        actions: [
          { key: ACTIONS.ELEMENT_READ, name: "View framework elements" },
          { key: ACTIONS.ELEMENT_MANAGE, name: "Manage elements + mappings" },
        ],
      },
      {
        name: "Cross References",
        route: "/cross-references/elements",
        routeSeo: "cross-references",
        icon: "git-compare",
        actions: [
          { key: ACTIONS.ASSESSMENT_READ, name: "View cross-references / rcmap" },
          { key: ACTIONS.ASSESSMENT_MANAGE, name: "Author conformance questions / responses" },
        ],
      },
      {
        name: "Framework Catalog",
        route: "/framework-catalog",
        routeSeo: "framework-catalog",
        icon: "book-open",
        actions: [
          { key: ACTIONS.FRAMEWORK_CATALOG_READ, name: "Browse framework catalog" },
          { key: ACTIONS.FRAMEWORK_CATALOG_SUBSCRIBE, name: "Subscribe to framework" },
        ],
      },
      {
        name: "My Frameworks",
        route: "/my-frameworks",
        routeSeo: "my-frameworks",
        icon: "book-open",
        actions: [
          { key: ACTIONS.MY_FRAMEWORK_READ, name: "View my framework subscriptions" },
          { key: ACTIONS.MY_FRAMEWORK_DELETE, name: "Remove a framework subscription" },
        ],
      },
    ],
  },
];
